-- Phase 2b : INSERT des nouveaux diplômes (générés automatiquement)
-- Total: 586 diplômes

START TRANSACTION;
INSERT IGNORE INTO ecolecamerdb.diplomes (nom_dip, categorie_id, niveau) VALUES
  ('BTS Assurances', 5, 'Bac'),
  ('BTS Génie civil - travaux publics', 5, 'Bac'),
  ('BTS Productions végétales', 5, 'Bac'),
  ('BTS Technique commerciale agricole', 5, 'Bac'),
  ('BTS Banque', 5, 'Bac'),
  ('DSEP Imagerie médicale', 25, 'Bac'),
  ('DSEP Technique de laboratoire médical', 25, 'Bac'),
  ('BTS Aquaculture', 5, 'Bac'),
  ('BTS Génie civil - bâtiments', 5, 'Bac'),
  ('BTS Génie mécanique', 5, 'Bac'),
  ('BTS Information-communication', 5, 'Bac'),
  ('BTS Informatique industrielle', 5, 'Bac'),
  ('DSEP Soins infirmiers', 25, 'Bac'),
  ('DSEP Ressources humaines', 25, 'Bac'),
  ('DSEP Études pharmaceutiques', 25, 'Bac'),
  ('DSEP Kinésithérapie', 25, 'Bac'),
  ('DSEP Santé de la reproduction', 25, 'Bac'),
  ('DSEP Études médicales', 25, 'Bac'),
  ('DSEP Physiothérapie', 25, 'Bac'),
  ('HND Banque et finance', 26, 'Bac'),
  ('HND Assurances', 26, 'Bac'),
  ('Licence Pro Assurances', 18, 'Bacc'),
  ('DSEP Télécommunications et réseaux', 25, 'Bac'),
  ('Licence Pro Maintenance informatique et réseaux', 18, 'Bacc'),
  ('Licence Pro Gestion informatique', 18, 'Bacc'),
  ('BTS Maintenance informatique', 5, 'Bac'),
  ('DSEP Maintenance informatique', 25, 'Bac'),
  ('DSEP Secrétariat et bureautique', 25, 'Bac'),
  ('Bachelor Assurances', 14, 'Bacc'),
  ('Bachelor Économie et gestion agricoles', 14, 'Bacc'),
  ('Bachelor Études forestières et conservation', 14, 'Bacc'),
  ('Bachelor Génie civil et environnemental', 14, 'Bacc'),
  ('Bachelor Ingénierie du textile et des fibres', 14, 'Bacc'),
  ('Bachelor Ingénierie mécanique', 14, 'Bacc'),
  ('Bachelor Management et entrepreneurial', 14, 'Bacc'),
  ('Bachelor Sciences informatiques', 14, 'Bacc'),
  ('Bachelor Technologie alimentaire', 14, 'Bacc'),
  ('ATD Boulangerie et transformation des aliments', 26, 'Bac'),
  ('ATD Comptabilité', 26, 'Bac'),
  ('HND Comptabilité', 26, 'Bac'),
  ('Licence Pro Comptabilité', 18, 'Bacc'),
  ('ATD Fabrication mécanique', 26, 'Bac'),
  ('ATD Ingénierie électrique', 26, 'Bac'),
  ('ATD Sciences du bâtiment', 26, 'Bac'),
  ('HND Économie domestique', 26, 'Bac'),
  ('HND Études de secrétariat', 26, 'Bac'),
  ('Licence Pro Études de secrétariat', 18, 'Bacc'),
  ('HND Ingénierie informatique', 26, 'Bac'),
  ('HND Didactique', 26, 'Bac'),
  ('Bachelor Études d''élevage', 14, 'Bacc');
COMMIT;

START TRANSACTION;
INSERT IGNORE INTO ecolecamerdb.diplomes (nom_dip, categorie_id, niveau) VALUES
  ('Bachelor Génie agricole', 14, 'Bacc'),
  ('Bachelor Génie électrique et informatique', 14, 'Bacc'),
  ('Bachelor Ingénierie industrielle et des systèmes', 14, 'Bacc'),
  ('Bachelor Ingénieur chimiste', 14, 'Bacc'),
  ('Bachelor Secrétariat exécutif', 14, 'Bacc'),
  ('ATD Affaires et informatique', 26, 'Bac'),
  ('ATD Bureautique', 26, 'Bac'),
  ('ATD Enseignement et formation', 26, 'Bac'),
  ('ATD Génie logiciel et informatique', 26, 'Bac'),
  ('ATD Maintenance du matériel informatique', 26, 'Bac'),
  ('ATD Stylisme et habillement', 26, 'Bac'),
  ('HND Éducation', 26, 'Bac'),
  ('HND Ingénierie électrique et électronique', 26, 'Bac'),
  ('HND Ingénierie mécanique', 26, 'Bac'),
  ('Licence Pro Ingénierie mécanique', 18, 'Bacc'),
  ('HND Agriculture et sciences de l''alimentation', 26, 'Bac'),
  ('HND Orientation professionnelle et conseil aux étudiants', 26, 'Bac'),
  ('HPD Petites et moyennes entreprises', 26, 'Bac'),
  ('HND Études professionnelles en éducation', 26, 'Bac'),
  ('HPD Carrières judiciaires', 26, 'Bac'),
  ('HPD Ressources humaines et management', 26, 'Bac'),
  ('BTS Informatique', 5, 'Bac'),
  ('BTS Automatismes industriels', 5, 'Bac'),
  ('HND Études professionnelles en éducation - deuxième cycle du secondaire', 26, 'Bac'),
  ('HND Gestion et administration de l''éducation', 26, 'Bac'),
  ('HND Planification et développement de l''éducation', 26, 'Bac'),
  ('HND Infirmier d''état', 26, 'Bac'),
  ('HPD Infirmier d''état', 26, 'Bac'),
  ('Licence Pro Infirmier d''état', 18, 'Bacc'),
  ('HND Génie civil et structurel', 26, 'Bac'),
  ('HND Tourisme et gestion hôtelière', 26, 'Bac'),
  ('HND Études de laboratoire médical', 26, 'Bac'),
  ('HND Nutrition et diététique', 26, 'Bac'),
  ('HND Études professionnelles en éducation - petite enfance', 26, 'Bac'),
  ('HPD Études de laboratoire médical', 26, 'Bac'),
  ('Licence Pro Études de laboratoire médical', 18, 'Bacc'),
  ('HND Soins infirmiers', 26, 'Bac'),
  ('HPD Soins infirmiers', 26, 'Bac'),
  ('Licence Pro Soins infirmiers', 18, 'Bacc'),
  ('HND Affaires et information', 26, 'Bac'),
  ('HND Éducation et développement professionnel', 26, 'Bac'),
  ('HND Journalisme', 26, 'Bac'),
  ('HND La gestion des soins de santé', 26, 'Bac'),
  ('HPD Comptabilité', 26, 'Bac'),
  ('HND Métallurgie minière et extractive', 26, 'Bac'),
  ('HPD Métallurgie minière et extractive', 26, 'Bac'),
  ('Master Pro Métallurgie minière et extractive', 22, 'Licence'),
  ('HND Technologie du génie pétrolier', 26, 'Bac'),
  ('HPD Technologie du génie pétrolier', 26, 'Bac'),
  ('HND Santé de la reproduction', 26, 'Bac');
COMMIT;

START TRANSACTION;
INSERT IGNORE INTO ecolecamerdb.diplomes (nom_dip, categorie_id, niveau) VALUES
  ('HPD Santé de la reproduction', 26, 'Bac'),
  ('HND Études de laboratoire', 26, 'Bac'),
  ('HPD Carrières juridiques', 26, 'Bac'),
  ('HPD Ressources humaines', 26, 'Bac'),
  ('HPD Études médicales', 26, 'Bac'),
  ('HPD Kinésithérapie', 26, 'Bac'),
  ('HPD Techniques de santé publique', 26, 'Bac'),
  ('HPD Technique de laboratoire médical', 26, 'Bac'),
  ('HND Logistique et transports', 26, 'Bac'),
  ('HPD Banque et finance', 26, 'Bac'),
  ('HPD Génie civil et structurel', 26, 'Bac'),
  ('HND Sciences animales appliquées', 26, 'Bac'),
  ('HPD Sciences animales appliquées', 26, 'Bac'),
  ('HND Physiothérapie', 26, 'Bac'),
  ('HPD Physiothérapie', 26, 'Bac'),
  ('HND Sciences de l''alimentation et nutrition', 26, 'Bac'),
  ('HPD Sciences de l''alimentation et nutrition', 26, 'Bac'),
  ('HND Beauty therapy', 26, 'Bac'),
  ('HPD Gestion des petites et moyennes organisations', 26, 'Bac'),
  ('HPD Études pharmaceutiques', 26, 'Bac'),
  ('HPD La gestion des soins de santé', 26, 'Bac'),
  ('HPD Arts de la scène et cinématographie', 26, 'Bac'),
  ('HND Arts de la scène et cinématographie', 26, 'Bac'),
  ('DSEP Génie informatique', 25, 'Bac'),
  ('DSEP Techniques de santé publique', 25, 'Bac'),
  ('Licence Pro Didactique - planification de l''éducation et développement du curriculum', 18, 'Bacc'),
  ('Licence Pro Agriculture', 18, 'Bacc'),
  ('Licence Pro Développement communautaire', 18, 'Bacc'),
  ('Licence Pro Économie et sociologie rurale', 18, 'Bacc'),
  ('Licence Pro Gestion de coopérative', 18, 'Bacc'),
  ('Licence Pro Communauté et éducation des adultes', 18, 'Bacc'),
  ('Licence Pro Didactique de la philosophie', 18, 'Bacc'),
  ('Licence Pro Enseignement pédagogique', 18, 'Bacc'),
  ('Licence Pro Orientation et conseil', 18, 'Bacc'),
  ('Licence Pro Sciences économiques', 18, 'Bacc'),
  ('Licence Pro Arts de la scène et cinématographie', 18, 'Bacc'),
  ('Master Pro Arts de la scène et cinématographie', 22, 'Licence'),
  ('Master Pro Comptabilité', 22, 'Licence'),
  ('Master Pro Marketing', 22, 'Licence'),
  ('Licence Pro Sciences animales appliquées', 18, 'Bacc'),
  ('Master Pro Sciences animales appliquées', 22, 'Licence'),
  ('DSEP Fabrication mécanique', 25, 'Bac'),
  ('DSEP Techniques pharmaceutiques', 25, 'Bac'),
  ('Licence Pro Secrétariat exécutif', 18, 'Bacc'),
  ('Licence Pro Agronomie et scinces du sol', 18, 'Bacc'),
  ('Licence Pro Économie domestique', 18, 'Bacc'),
  ('Licence Pro Études environnementales et gestion des ressources hydriques', 18, 'Bacc'),
  ('Licence Pro Nutrition humaine et restauration', 18, 'Bacc'),
  ('Licence Pro Développement humain', 18, 'Bacc'),
  ('Licence Pro Mathématiques', 18, 'Bacc');
COMMIT;

START TRANSACTION;
INSERT IGNORE INTO ecolecamerdb.diplomes (nom_dip, categorie_id, niveau) VALUES
  ('Licence Pro Droit', 18, 'Bacc'),
  ('Licence Pro Communication de masse et journalisme', 18, 'Bacc'),
  ('Master Pro Management', 22, 'Licence'),
  ('Licence Pro Génie civil et structurel', 18, 'Bacc'),
  ('Master Pro Génie civil et structurel', 22, 'Licence'),
  ('Licence Pro Sciences de l''alimentation et nutrition', 18, 'Bacc'),
  ('Master Pro Sciences de l''alimentation et nutrition', 22, 'Licence'),
  ('Master Pro Soins infirmiers', 22, 'Licence'),
  ('Diplôme d''Ingénieur Physique chimie', 19, 'Bac'),
  ('Diplôme d''Ingénieur Informatique', 19, 'Bac'),
  ('DSEP Électronique et électrotechnique', 25, 'Bac'),
  ('DSEP Automatique et informatique industrielle', 25, 'Bac'),
  ('DSEP Français et sa didactique', 25, 'Bac'),
  ('DSEP Svt et leurs didactiques', 25, 'Bac'),
  ('Licence Pro Didactique des sciences', 18, 'Bacc'),
  ('Licence Pro Psychopédagogie', 18, 'Bacc'),
  ('DSEP Anglais et sa didactique', 25, 'Bac'),
  ('DSEP Mathématiques et leurs didactiques', 25, 'Bac'),
  ('Licence Pro Didactique des lettres', 18, 'Bacc'),
  ('Licence Pro Langues et sciences humaines', 18, 'Bacc'),
  ('Bachelor Comptabilité', 14, 'Bacc'),
  ('Bachelor Soins infirmiers', 14, 'Bacc'),
  ('HND Électrique et électronique', 26, 'Bac'),
  ('HND Ingénierie', 26, 'Bac'),
  ('HND Secrétariat exécutif et service public et administration', 26, 'Bac'),
  ('HND Secrétariat exécutif', 26, 'Bac'),
  ('HND Obstétrique', 26, 'Bac'),
  ('Capacité en Droit Droit', 28, 'Bac'),
  ('Bachelor Études de laboratoire médical', 14, 'Bacc'),
  ('HND Fabrication mécanique', 26, 'Bac'),
  ('HND Génie logiciel et informatique', 26, 'Bac'),
  ('HND Maintenance du matériel', 26, 'Bac'),
  ('HND Système d''alimentation électrique', 26, 'Bac'),
  ('Master Pro Maintenance des systèmes informatiques', 22, 'Licence'),
  ('Doctorat Maintenance des systèmes informatiques', 3, 'Master'),
  ('Doctorat Génie électrique', 3, 'Master'),
  ('Master Pro Informatique industrielle', 22, 'Licence'),
  ('Doctorat Informatique industrielle', 3, 'Master'),
  ('Licence Pro Télécommunications et réseaux', 18, 'Bacc'),
  ('Doctorat Télécommunications et réseaux', 3, 'Master'),
  ('Licence Pro Banque', 18, 'Bacc'),
  ('Licence Chirurgie dentaire', 17, 'Bacc'),
  ('Master Chirurgie dentaire', 20, 'Licence'),
  ('Doctorat Chirurgie dentaire', 3, 'Master'),
  ('Licence Médecine', 17, 'Bacc'),
  ('Master Médecine', 20, 'Licence'),
  ('Doctorat Médecine', 3, 'Master'),
  ('Licence Pro Énergétique et génie climatique', 18, 'Bacc'),
  ('Licence Pro Ingénierie électrique', 18, 'Bacc'),
  ('Licence Pro Maintenance après vente des automobiles', 18, 'Bacc');
COMMIT;

START TRANSACTION;
INSERT IGNORE INTO ecolecamerdb.diplomes (nom_dip, categorie_id, niveau) VALUES
  ('Licence Pro Génie civil - travaux publics', 18, 'Bacc'),
  ('Licence Études vétérinaires', 17, 'Bacc'),
  ('Master Études vétérinaires', 20, 'Licence'),
  ('Doctorat Études vétérinaires', 3, 'Master'),
  ('Licence Pharmacie', 17, 'Bacc'),
  ('Master Pharmacie', 20, 'Licence'),
  ('Doctorat Pharmacie', 3, 'Master'),
  ('Licence Pro Finance-comptabilité', 18, 'Bacc'),
  ('Licence Pro Maintenance du matériel biomédical', 18, 'Bacc'),
  ('BTS Architecture d''intérieur et design de création', 5, 'Bac'),
  ('BTS Dessin animé', 5, 'Bac'),
  ('BTS Modélisme et organisation de production de l''habillement', 5, 'Bac'),
  ('BTS Génie forestier', 5, 'Bac'),
  ('BTS Information et communication', 5, 'Bac'),
  ('BTS Métiers du bois', 5, 'Bac'),
  ('DSEP Télécommunications', 25, 'Bac'),
  ('BTS Technologie de l''information et de la communication', 5, 'Bac'),
  ('Licence Pro Innovation et information stratégique', 18, 'Bacc'),
  ('Master Innovation et information stratégique', 20, 'Licence'),
  ('HND Études de secrétariat, administration et service public', 26, 'Bac'),
  ('DSEP Automatique', 25, 'Bac'),
  ('DSEP Petites et moyennes organisations', 25, 'Bac'),
  ('DSEP Maintenance des systèmes informatiques', 25, 'Bac'),
  ('DSEP Informatique industrielle', 25, 'Bac'),
  ('DSEP Santé au travail', 25, 'Bac'),
  ('DSEP Métiers du tourisme', 25, 'Bac'),
  ('DSEP Génie civil', 25, 'Bac'),
  ('DSEP Assurances', 25, 'Bac'),
  ('DSEP Génie électrique', 25, 'Bac'),
  ('DSEP Gestion des ressources humaines', 25, 'Bac'),
  ('DSEP Métiers de l''hôtellerie', 25, 'Bac'),
  ('DSEP Électrique et électrotechnique', 25, 'Bac'),
  ('DSEP Action commerciale', 25, 'Bac'),
  ('DSEP Carrières juridiques', 25, 'Bac'),
  ('DSEP Sage-femme', 25, 'Bac'),
  ('BTS Gestion des entreprises et restauration', 5, 'Bac'),
  ('BTS Atmosphérique', 5, 'Bac'),
  ('BTS Chimie de la pollution', 5, 'Bac'),
  ('BTS Gestion des risques chimiques', 5, 'Bac'),
  ('BTS Mine', 5, 'Bac'),
  ('BTS Communication de l''entreprise', 5, 'Bac'),
  ('BTS Chimie et traitement des eaux', 5, 'Bac'),
  ('BTS Environnementaux et hospitaliers', 5, 'Bac'),
  ('Licence Pro Administration et planification', 18, 'Bacc'),
  ('Licence Pro Fondamentaux de l''éducation', 18, 'Bacc'),
  ('Licence Pro Psychopédagogie et orthopédagogie', 18, 'Bacc'),
  ('Licence Pro Sciences médicales', 18, 'Bacc'),
  ('Licence Pro Didactique des disciplines', 18, 'Bacc'),
  ('Licence Pro Pédagogie', 18, 'Bacc'),
  ('Licence Pro Sciences médico-sanitaires', 18, 'Bacc');
COMMIT;

START TRANSACTION;
INSERT IGNORE INTO ecolecamerdb.diplomes (nom_dip, categorie_id, niveau) VALUES
  ('DUT Génie civil', 12, 'Bacc'),
  ('Diplôme d''Ingénieur de Travaux Génie civil', 32, 'Bac'),
  ('Diplôme d''Ingénieur Génie civil', 19, 'Bac'),
  ('DUT Génie rural', 12, 'Bacc'),
  ('Diplôme d''Ingénieur de Travaux Génie rural', 32, 'Bac'),
  ('Diplôme d''Ingénieur Génie rural', 19, 'Bac'),
  ('DUT Génie urbain', 12, 'Bacc'),
  ('Diplôme d''Ingénieur de Travaux Génie urbain', 32, 'Bac'),
  ('Diplôme d''Ingénieur Génie urbain', 19, 'Bac'),
  ('DUT Topographie-cadastre', 12, 'Bacc'),
  ('Diplôme d''Ingénieur de Travaux Topographie-cadastre', 32, 'Bac'),
  ('Diplôme d''Ingénieur Topographie-cadastre', 19, 'Bac'),
  ('Licence Pro Comptabilité et finances -  contrôle de gestion', 18, 'Bacc'),
  ('Licence Pro Merchandising', 18, 'Bacc'),
  ('Licence Pro Comptabilité et finances', 18, 'Bacc'),
  ('Licence Pro Assistance adminsitrative bilingue', 18, 'Bacc'),
  ('Licence Pro Informatique multimédia', 18, 'Bacc'),
  ('Licence Pro Réseaux et télécom', 18, 'Bacc'),
  ('Licence Pro Informatique', 18, 'Bacc'),
  ('Licence Pro Ameublement et construction du bois', 18, 'Bacc'),
  ('Licence Pro Génie du bois', 18, 'Bacc'),
  ('Licence Informatique de gestion', 17, 'Bacc'),
  ('Licence Commercialisation du bois', 17, 'Bacc'),
  ('Master Pro Commercialisation du bois', 22, 'Licence'),
  ('Licence Génie thermique et énergétique', 17, 'Bacc'),
  ('Master Pro Génie thermique et énergétique', 22, 'Licence'),
  ('Licence Banque et établissements financiers', 17, 'Bacc'),
  ('Master Banque et établissements financiers', 20, 'Licence'),
  ('Licence Informatique', 17, 'Bacc'),
  ('Master Informatique', 20, 'Licence'),
  ('Licence Ressources humaines', 17, 'Bacc'),
  ('Master Ressources humaines', 20, 'Licence'),
  ('Licence Sciences de l''ingénieur', 17, 'Bacc'),
  ('Master Sciences de l''ingénieur', 20, 'Licence'),
  ('Licence Architecture', 17, 'Bacc'),
  ('Master Architecture', 20, 'Licence'),
  ('Doctorat Architecture', 3, 'Master'),
  ('Licence Sciences juridiques et politiques', 17, 'Bacc'),
  ('Master Pro Ressources humaines', 22, 'Licence'),
  ('Licence Construction du bois', 17, 'Bacc'),
  ('Master Pro Construction du bois', 22, 'Licence'),
  ('Licence Comptabilité et finances', 17, 'Bacc'),
  ('Master Comptabilité et finances', 20, 'Licence'),
  ('Licence Marketing et vente', 17, 'Bacc'),
  ('Master Marketing et vente', 20, 'Licence'),
  ('Licence Sciences de la vie', 17, 'Bacc'),
  ('Master Sciences de la vie', 20, 'Licence'),
  ('Licence Transport et logistique', 17, 'Bacc'),
  ('Master Transport et logistique', 20, 'Licence'),
  ('Licence Sciences sociales', 17, 'Bacc');
COMMIT;

START TRANSACTION;
INSERT IGNORE INTO ecolecamerdb.diplomes (nom_dip, categorie_id, niveau) VALUES
  ('Doctorat Sciences sociales', 3, 'Master'),
  ('Bachelor La gestion des soins de santé', 14, 'Bacc'),
  ('Bachelor Technicien dentaire', 14, 'Bacc'),
  ('Bachelor Information et technologie', 14, 'Bacc'),
  ('Bachelor Agriculture, économie et gestion', 14, 'Bacc'),
  ('Bachelor Kinésithérapie', 14, 'Bacc'),
  ('Bachelor Radiologie', 14, 'Bacc'),
  ('Bachelor Technologie de la pharmacie', 14, 'Bacc'),
  ('HPD Technologie de la pharmacie', 26, 'Bac'),
  ('HND Échographie', 26, 'Bac'),
  ('Bachelor Échographie', 14, 'Bacc'),
  ('Bachelor Nutrition et diététique', 14, 'Bacc'),
  ('Licence Économie de gestion', 17, 'Bacc'),
  ('Licence Comptabilité - finance', 17, 'Bacc'),
  ('Master Comptabilité - finance', 20, 'Licence'),
  ('Licence Théologie', 17, 'Bacc'),
  ('Master Théologie', 20, 'Licence'),
  ('Doctorat Théologie', 3, 'Master'),
  ('Master Cinéma et arts du spectacle', 20, 'Licence'),
  ('Doctorat Cinéma et arts du spectacle', 3, 'Master'),
  ('Master Communication sociale', 20, 'Licence'),
  ('Doctorat Communication sociale', 3, 'Master'),
  ('Master Énergie et génie énergétique', 20, 'Licence'),
  ('Doctorat Énergie et génie énergétique', 3, 'Master'),
  ('Master Gestion de la communication marketing et publicitaire', 20, 'Licence'),
  ('Doctorat Gestion de la communication marketing et publicitaire', 3, 'Master'),
  ('Licence Management audit et contrôle', 17, 'Bacc'),
  ('Licence Communication, marketing et vente', 17, 'Bacc'),
  ('Licence Sciences infirmières', 17, 'Bacc'),
  ('Master Commerce', 20, 'Licence'),
  ('Doctorat Commerce', 3, 'Master'),
  ('Master Édition et multimédia', 20, 'Licence'),
  ('Doctorat Édition et multimédia', 3, 'Master'),
  ('Master Génie civil', 20, 'Licence'),
  ('Doctorat Génie civil', 3, 'Master'),
  ('HND Affaires et informatique', 26, 'Bac'),
  ('HND Conservation management', 26, 'Bac'),
  ('Licence Pro Management des achats et vente à l''international', 18, 'Bacc'),
  ('Licence Pro Organisation et administration', 18, 'Bacc'),
  ('Master Pro Organisation et administration', 22, 'Licence'),
  ('Licence Pro Système réseaux et télécommunication', 18, 'Bacc'),
  ('Master Pro Système réseaux et télécommunication', 22, 'Licence'),
  ('Licence Pro Audit', 18, 'Bacc'),
  ('Licence Pro Administration publique', 18, 'Bacc'),
  ('Licence Pro Génie mécanique et productif', 18, 'Bacc'),
  ('Licence Pro Réseaux et télécommunication', 18, 'Bacc'),
  ('Licence Pro Tourisme', 18, 'Bacc'),
  ('Master Pro Tourisme', 22, 'Licence'),
  ('Licence Pro Gestion technico-commerciale', 18, 'Bacc'),
  ('Licence Pro Droit des métiers', 18, 'Bacc');
COMMIT;

START TRANSACTION;
INSERT IGNORE INTO ecolecamerdb.diplomes (nom_dip, categorie_id, niveau) VALUES
  ('Licence Pro Métier du barreau', 18, 'Bacc'),
  ('Licence Pro Marketing - marchandisage', 18, 'Bacc'),
  ('Master Pro Commerce international', 22, 'Licence'),
  ('Licence Pro Métier du notaire', 18, 'Bacc'),
  ('Licence Pro Production et gestion de l''énergie', 18, 'Bacc'),
  ('Licence Pro Contrôle de gestion', 18, 'Bacc'),
  ('Licence Pro Gestion des projets et entrepreneuriat', 18, 'Bacc'),
  ('Master Pro Comptabilité et gestion des entreprises', 22, 'Licence'),
  ('Master Télécommunications et réseaux', 20, 'Licence'),
  ('Master Distribution', 20, 'Licence'),
  ('Master Gestion des ressources humaines', 20, 'Licence'),
  ('Master Communication de données et mise en réseau', 20, 'Licence'),
  ('Master Master international en administration des affaires', 20, 'Licence'),
  ('Master Gouvernance et action publique', 20, 'Licence'),
  ('Master Micro-finance (en ligne)', 20, 'Licence'),
  ('Master Banque - finance', 20, 'Licence'),
  ('Master Management et systèmes d''information', 20, 'Licence'),
  ('Master Santé publique', 20, 'Licence'),
  ('Master Anesthésie et réanimation', 20, 'Licence'),
  ('Master Santé de la reproduction', 20, 'Licence'),
  ('Master Touristique et social', 20, 'Licence'),
  ('Doctorat Touristique et social', 3, 'Master'),
  ('Master Finance et contrôle de gestion', 20, 'Licence'),
  ('Master Marketing', 20, 'Licence'),
  ('Master Démographie et statistique appliquée', 20, 'Licence'),
  ('Master Planification du développement', 20, 'Licence'),
  ('Master Management et developpement des projets en afrique', 20, 'Licence'),
  ('Master Audit et contrôle de gestion', 20, 'Licence'),
  ('Master Marketing et stratégies', 20, 'Licence'),
  ('Master Analyses médicales', 20, 'Licence'),
  ('Master Microbiologie', 20, 'Licence'),
  ('Master Gestion hospitalière', 20, 'Licence'),
  ('Licence Pro Activités et techniques de communication', 18, 'Bacc'),
  ('Licence Pro Génie indutsriel et technologique', 18, 'Bacc'),
  ('Licence Pro Méthodes et management de la qualité', 18, 'Bacc'),
  ('Licence Pro Études médicales', 18, 'Bacc'),
  ('Licence Pro Imagerie médicale', 18, 'Bacc'),
  ('Licence Pro Technique de laboratoire médical', 18, 'Bacc'),
  ('Master Pro Banque', 22, 'Licence'),
  ('Licence Pro Comptabilité et gestion financière', 18, 'Bacc'),
  ('Licence Pro Droit fiscal', 18, 'Bacc'),
  ('Licence Pro Commerce  - management et gestion de la relation clientèle', 18, 'Bacc'),
  ('Licence Pro Conception et création multimédia', 18, 'Bacc'),
  ('Licence Pro Électrosonography', 18, 'Bacc'),
  ('Licence Pro Études pharmaceutiques', 18, 'Bacc'),
  ('Licence Pro Techniques de santé publique', 18, 'Bacc'),
  ('Licence Pro Analyse concepteur des systèmes informatiques', 18, 'Bacc'),
  ('Licence Pro Communication publicitaire', 18, 'Bacc'),
  ('Master Pro Communication publicitaire', 22, 'Licence'),
  ('Licence Pro Création d''entreprises et gestion des projets', 18, 'Bacc');
COMMIT;

START TRANSACTION;
INSERT IGNORE INTO ecolecamerdb.diplomes (nom_dip, categorie_id, niveau) VALUES
  ('Master Pro Droit des affaires', 22, 'Licence'),
  ('HND Programmation informatique', 26, 'Bac'),
  ('HND Administration et santé publique', 26, 'Bac'),
  ('HND Marketing et publicité', 26, 'Bac'),
  ('HND Ressource humaine', 26, 'Bac'),
  ('HND Transport et logistique', 26, 'Bac'),
  ('HND Technologie de l''information et de la communication', 26, 'Bac'),
  ('HPD Radiologie et technologie à ultrasons', 26, 'Bac'),
  ('HPD Thérapie dentaire', 26, 'Bac'),
  ('BTS Développement agropastoral', 5, 'Bac'),
  ('BTS Métiers d''entrepreneur agéopasoral', 5, 'Bac'),
  ('BTS Métiers agent de développement agropastoral', 5, 'Bac'),
  ('MBA Tourisme', 8, 'Licence'),
  ('Doctorat Communication de données et mise en réseau', 3, 'Master'),
  ('MBA Commerce - vente', 8, 'Licence'),
  ('Capacité en Droit Capacité en droit', 28, 'Bac'),
  ('Bachelor Banque', 14, 'Bacc'),
  ('Master Banque', 20, 'Licence'),
  ('Doctorat Banque', 3, 'Master'),
  ('Bachelor Ingénierie informatique', 14, 'Bacc'),
  ('Master Assurances', 20, 'Licence'),
  ('Doctorat Assurances', 3, 'Master'),
  ('DSEP Informatique de gestion', 25, 'Bac'),
  ('BTS Bâtiments', 5, 'Bac'),
  ('Licence Pro Comptabilité et gestion des entreprises', 18, 'Bacc'),
  ('BTS Technique de laboratoire médical', 5, 'Bac'),
  ('BTS Droit des affaires', 5, 'Bac'),
  ('BTS Soins infirmiers', 5, 'Bac'),
  ('BTS Techniques de santé publique', 5, 'Bac'),
  ('BTS Tourisme', 5, 'Bac'),
  ('Bachelor Journalisme / gestion de l''impression', 14, 'Bacc'),
  ('Bachelor Communication de données et mise en réseau', 14, 'Bacc'),
  ('Bachelor Information et communication', 14, 'Bacc'),
  ('Master Information et communication', 20, 'Licence'),
  ('Doctorat Information et communication', 3, 'Master'),
  ('Bachelor Technologie de l''information et de la communication', 14, 'Bacc'),
  ('Master Technologie de l''information et de la communication', 20, 'Licence'),
  ('Doctorat Technologie de l''information et de la communication', 3, 'Master'),
  ('Bachelor Administration des affaires', 14, 'Bacc'),
  ('Master Administration des affaires', 20, 'Licence'),
  ('Doctorat Administration des affaires', 3, 'Master'),
  ('Bachelor Génie logiciel', 14, 'Bacc'),
  ('Bachelor Télécommunications', 14, 'Bacc'),
  ('Master Télécommunications', 20, 'Licence'),
  ('Doctorat Télécommunications', 3, 'Master'),
  ('HND Boulangerie et transformation des aliments', 26, 'Bac'),
  ('HND Dessin de mode', 26, 'Bac'),
  ('HND Formation continue et à distance', 26, 'Bac'),
  ('Master Management', 20, 'Licence'),
  ('Doctorat Management', 3, 'Master');
COMMIT;

START TRANSACTION;
INSERT IGNORE INTO ecolecamerdb.diplomes (nom_dip, categorie_id, niveau) VALUES
  ('Bachelor Administration des affaires et économie', 14, 'Bacc'),
  ('Master Administration des affaires et économie', 20, 'Licence'),
  ('Master Génie logiciel', 20, 'Licence'),
  ('Doctorat Génie logiciel', 3, 'Master'),
  ('Bachelor Réseaux et systèmes d''informations', 14, 'Bacc'),
  ('Master Réseaux et systèmes d''informations', 20, 'Licence'),
  ('Doctorat Réseaux et systèmes d''informations', 3, 'Master'),
  ('Bachelor Management pour le développement durable', 14, 'Bacc'),
  ('HND Gestion bancaire et financière', 26, 'Bac'),
  ('HND Vêtements et textiles', 26, 'Bac'),
  ('DSEP Droit des affaires', 25, 'Bac'),
  ('DSEP Bâtiments', 25, 'Bac'),
  ('DSEP Mécanique automobile', 25, 'Bac'),
  ('DSEP Thermique et énergie', 25, 'Bac'),
  ('DSEP Urbanisme', 25, 'Bac'),
  ('DSEP Construction mécanique', 25, 'Bac'),
  ('DSEP Travaux publics', 25, 'Bac'),
  ('BTS Génie civil - aménagement urbain', 5, 'Bac'),
  ('BTS Logistique et transports', 5, 'Bac'),
  ('BTS Chaudronnerie', 5, 'Bac'),
  ('BTS Agriculture', 5, 'Bac'),
  ('DSEP Agriculture', 25, 'Bac'),
  ('DSEP Productions végétales', 25, 'Bac'),
  ('DSEP Gestion et maîtrise de l''eau', 25, 'Bac'),
  ('DSEP Production animale', 25, 'Bac'),
  ('BTS Technico-commerciale agricole', 5, 'Bac'),
  ('DSEP Technico-commerciale agricole', 25, 'Bac'),
  ('BTS Génie du bois - menuiserie et ébénisterie', 5, 'Bac'),
  ('BTS Productique et commercialisation du bois', 5, 'Bac'),
  ('Licence Productique et commercialisation du bois', 17, 'Bacc'),
  ('Licence Pro Génie logiciel et réseaux', 18, 'Bacc'),
  ('Licence Pro Réseaux et multimédia', 18, 'Bacc'),
  ('Licence Pro Italian languages', 18, 'Bacc'),
  ('Licence Pro Informatique industrielle - réseaux locaux', 18, 'Bacc'),
  ('Licence Pro Langues et culture camerounaise spécifique', 18, 'Bacc'),
  ('Licence Pro Attaché de direction', 18, 'Bacc'),
  ('Master Commerce international', 20, 'Licence'),
  ('Doctorat Commerce international', 3, 'Master'),
  ('Licence Pro Commissariat aux comptes', 18, 'Bacc'),
  ('Licence Pro Communication et information', 18, 'Bacc'),
  ('Master Communication et information', 20, 'Licence'),
  ('Doctorat Communication et information', 3, 'Master'),
  ('Licence Pro Contrôle financier', 18, 'Bacc'),
  ('Licence Pro Droit des affaires et carrières juridiques', 18, 'Bacc'),
  ('Licence Pro Carrières juridiques', 18, 'Bacc'),
  ('Master Carrières juridiques', 20, 'Licence'),
  ('Doctorat Carrières juridiques', 3, 'Master'),
  ('Licence Pro Commerce international - transport et logistique', 18, 'Bacc'),
  ('Master Communication des organisations et relations publiques', 20, 'Licence'),
  ('Doctorat Communication des organisations et relations publiques', 3, 'Master');
COMMIT;

START TRANSACTION;
INSERT IGNORE INTO ecolecamerdb.diplomes (nom_dip, categorie_id, niveau) VALUES
  ('Licence Pro Comptabilité et fiscalité d''entreprise', 18, 'Bacc'),
  ('Master Comptabilité et fiscalité d''entreprise', 20, 'Licence'),
  ('Doctorat Comptabilité et fiscalité d''entreprise', 3, 'Master'),
  ('Master Droit', 20, 'Licence'),
  ('Doctorat Droit', 3, 'Master'),
  ('Master Finance et comptabilité', 20, 'Licence'),
  ('Doctorat Finance et comptabilité', 3, 'Master'),
  ('Licence Pro Gestion des entreprises et des administrations', 18, 'Bacc'),
  ('DSEP Commerce international', 25, 'Bac'),
  ('DSEP Génie forestier', 25, 'Bac'),
  ('DSEP Génie mécanique', 25, 'Bac'),
  ('DSEP Information-communication', 25, 'Bac'),
  ('DSEP Banque', 25, 'Bac'),
  ('DSEP Comptabilité et gestion des entreprises', 25, 'Bac'),
  ('BTS Expertise comptable', 5, 'Bac'),
  ('BTS Gestion des entreprises et administration', 5, 'Bac'),
  ('DSEP Gestion des entreprises et administration', 25, 'Bac'),
  ('DSEP Sciences pharmaceutiques', 25, 'Bac'),
  ('Master Génie électrique', 20, 'Licence'),
  ('Master Génie mécanique', 20, 'Licence'),
  ('Doctorat Génie mécanique', 3, 'Master'),
  ('Master Gestion des entreprises et des administrations', 20, 'Licence'),
  ('Doctorat Gestion des entreprises et des administrations', 3, 'Master'),
  ('Master Gestion logistique et transport', 20, 'Licence'),
  ('Doctorat Gestion logistique et transport', 3, 'Master'),
  ('Doctorat Informatique', 3, 'Master'),
  ('Licence Pro Maintenance informatique', 18, 'Bacc'),
  ('Licence Pro Management des entreprises touristiques', 18, 'Bacc'),
  ('Master Publicité', 20, 'Licence'),
  ('Doctorat Publicité', 3, 'Master'),
  ('Licence Pro Management commercial', 18, 'Bacc'),
  ('Licence Pro Tourisme et management de l''hébergement et produit du terroir', 18, 'Bacc'),
  ('Licence Pro Système informatiques et réseaux', 18, 'Bacc'),
  ('Master Kinésithérapie', 20, 'Licence'),
  ('Doctorat Kinésithérapie', 3, 'Master'),
  ('Licence Pro Génie informatique et réseaux', 18, 'Bacc'),
  ('Master Génie informatique et réseaux', 20, 'Licence'),
  ('Doctorat Génie informatique et réseaux', 3, 'Master'),
  ('Licence Pro Génie logiciel et bases de données', 18, 'Bacc'),
  ('Licence Pro Génie thermique et énergétique', 18, 'Bacc'),
  ('Licence Pro Guide touristique national', 18, 'Bacc'),
  ('Master Informatique de gestion', 20, 'Licence'),
  ('Doctorat Informatique de gestion', 3, 'Master'),
  ('Licence Pro Maintenance des systèmes industriels', 18, 'Bacc'),
  ('Master Maintenance des systèmes industriels', 20, 'Licence'),
  ('Doctorat Maintenance des systèmes industriels', 3, 'Master'),
  ('Licence Pro Production mécanique', 18, 'Bacc'),
  ('Licence Pro Affaire internationales', 18, 'Bacc'),
  ('Licence Pro Tourisme et management de l''animation', 18, 'Bacc'),
  ('Licence Pro Tourisme et management de l''hôtellerie de plein air', 18, 'Bacc');
COMMIT;

START TRANSACTION;
INSERT IGNORE INTO ecolecamerdb.diplomes (nom_dip, categorie_id, niveau) VALUES
  ('Licence Pro Ressources humaines', 18, 'Bacc'),
  ('Master Études médicales', 20, 'Licence'),
  ('Doctorat Études médicales', 3, 'Master'),
  ('Master Techniques de santé publique', 20, 'Licence'),
  ('Doctorat Techniques de santé publique', 3, 'Master'),
  ('Master Pro Comptabilité et finances', 22, 'Licence'),
  ('Licence Pro Entrepreneuriat', 18, 'Bacc'),
  ('Licence Pro Éducation civique', 18, 'Bacc'),
  ('Licence Pro Génie électrique et télécom', 18, 'Bacc'),
  ('Licence Pro Géographie', 18, 'Bacc'),
  ('Licence Pro Histoire', 18, 'Bacc'),
  ('Licence Pro Lettres modernes française', 18, 'Bacc'),
  ('Licence Pro Traduction', 18, 'Bacc'),
  ('Master Pro Traduction', 22, 'Licence'),
  ('Master Techniques pharmaceutiques', 20, 'Licence'),
  ('Doctorat Techniques pharmaceutiques', 3, 'Master'),
  ('Licence Pro Communication de l''entreprise', 18, 'Bacc'),
  ('Licence Pro Génie des réseaux et télécommunications', 18, 'Bacc'),
  ('Licence Pro Génie informatique', 18, 'Bacc'),
  ('Licence Pro Gestion de l''environnement', 18, 'Bacc'),
  ('Licence Pro Lettres modernes anglaises', 18, 'Bacc'),
  ('Licence Pro Langage des signes', 18, 'Bacc'),
  ('Master Pro Langage des signes', 22, 'Licence'),
  ('Licence Pro Génie mécanique - maintenance et après vente automobile', 18, 'Bacc'),
  ('Licence Pro Génie mécanique - fabrication et constructions mécanique', 18, 'Bacc'),
  ('BTS Art de la table et du service', 5, 'Bac'),
  ('BTS Hébergement', 5, 'Bac'),
  ('BTS Art culinaire', 5, 'Bac'),
  ('BTS Gestion hôtelière', 5, 'Bac'),
  ('BTS Vente et production touristique', 5, 'Bac'),
  ('DSEP Industries alimentaires', 25, 'Bac'),
  ('DSEP Diététique', 25, 'Bac'),
  ('BTS Industries de l''habillement', 5, 'Bac'),
  ('BTS Techniques commerciales et marketing', 5, 'Bac'),
  ('Master Pro Administration des affaires', 22, 'Licence'),
  ('Master Pro Interprétation des conférences', 22, 'Licence');
COMMIT;

