-- Phase 2 (public/private-university batch) — nouveaux diplômes
-- Généré automatiquement, NON EXÉCUTÉ — à valider avant tout INSERT
SET NAMES utf8mb4;

START TRANSACTION;
INSERT IGNORE INTO diplomes (nom_dip, categorie_id, niveau) VALUES
  ('Licence Gestion', 17, 'Bacc'),
  ('Master Gestion', 20, 'Licence'),
  ('Doctorat Gestion', 3, 'Master'),
  ('Licence Histoire et archéologie', 17, 'Bacc'),
  ('Master Histoire et archéologie', 20, 'Licence'),
  ('Doctorat Histoire et archéologie', 3, 'Master'),
  ('Licence Linguistiques et langues africaines', 17, 'Bacc'),
  ('Master Linguistiques et langues africaines', 20, 'Licence'),
  ('Doctorat Linguistiques et langues africaines', 3, 'Master'),
  ('Licence Géographie et planification', 17, 'Bacc'),
  ('Master Géographie et planification', 20, 'Licence'),
  ('Doctorat Géographie et planification', 3, 'Master'),
  ('Licence Droit public', 17, 'Bacc'),
  ('Master Droit public', 20, 'Licence'),
  ('Doctorat Droit public', 3, 'Master'),
  ('Licence Biologie', 17, 'Bacc'),
  ('Master Biologie', 20, 'Licence'),
  ('Doctorat Biologie', 3, 'Master'),
  ('Licence Physique', 17, 'Bacc'),
  ('Master Physique', 20, 'Licence'),
  ('Doctorat Physique', 3, 'Master'),
  ('Licence Sciences de l\'informatique', 17, 'Bacc'),
  ('Master Sciences de l\'informatique', 20, 'Licence'),
  ('Doctorat Sciences de l\'informatique', 3, 'Master'),
  ('Licence Sciences cliniques', 17, 'Bacc'),
  ('Master Sciences cliniques', 20, 'Licence'),
  ('Doctorat Sciences cliniques', 3, 'Master'),
  ('Licence Soins infirmiers et obstétricaux', 17, 'Bacc'),
  ('Licence Management', 17, 'Bacc'),
  ('Master Management', 20, 'Licence'),
  ('Licence Assurance et sécurité sociale', 17, 'Bacc'),
  ('Master Assurance et sécurité sociale', 20, 'Licence'),
  ('Licence Économie', 17, 'Bacc'),
  ('Master Économie', 20, 'Licence'),
  ('Doctorat Économie', 3, 'Master'),
  ('Licence Comptabilité', 17, 'Bacc'),
  ('Master Comptabilité', 20, 'Licence'),
  ('Doctorat Comptabilité', 3, 'Master'),
  ('Licence Langues anglaises', 17, 'Bacc'),
  ('Master Langues anglaises', 20, 'Licence'),
  ('Doctorat Langues anglaises', 3, 'Master'),
  ('Licence Art plastique et de la créativité', 17, 'Bacc'),
  ('Master Art plastique et de la créativité', 20, 'Licence'),
  ('Doctorat Art plastique et de la créativité', 3, 'Master'),
  ('Licence Droit privé anglophone', 17, 'Bacc'),
  ('Master Droit privé anglophone', 20, 'Licence'),
  ('Doctorat Droit privé anglophone', 3, 'Master'),
  ('Licence Sciences politiques', 17, 'Bacc'),
  ('Master Sciences politiques', 20, 'Licence'),
  ('Doctorat Sciences politiques', 3, 'Master');
COMMIT;

START TRANSACTION;
INSERT IGNORE INTO diplomes (nom_dip, categorie_id, niveau) VALUES
  ('Master Chimie', 20, 'Licence'),
  ('Doctorat Chimie', 3, 'Master'),
  ('Licence Sciences biologiques', 17, 'Bacc'),
  ('Master Sciences biologiques', 20, 'Licence'),
  ('Doctorat Sciences biologiques', 3, 'Master'),
  ('Licence Marketing', 17, 'Bacc'),
  ('Master Marketing', 20, 'Licence'),
  ('Licence Technologie et sciences alimentaires', 17, 'Bacc'),
  ('Master Technologie et sciences alimentaires', 20, 'Licence'),
  ('Licence Production agricole', 17, 'Bacc'),
  ('Licence Logistique et transport terrestre', 17, 'Bacc'),
  ('Master Logistique et transport terrestre', 20, 'Licence'),
  ('Licence Logistique et transport arérien', 17, 'Bacc'),
  ('Master Logistique et transport arérien', 20, 'Licence'),
  ('Licence Douanes', 17, 'Bacc'),
  ('Master Douanes', 20, 'Licence'),
  ('Licence Pédagogie', 17, 'Bacc'),
  ('Licence Psychologie educative', 17, 'Bacc'),
  ('Licence Soins et éducation de la petite enfance', 17, 'Bacc'),
  ('Licence Système d\'éducation', 17, 'Bacc'),
  ('Licence Philosophie', 17, 'Bacc'),
  ('Master Philosophie', 20, 'Licence'),
  ('Doctorat Philosophie', 3, 'Master'),
  ('Licence Banque', 17, 'Bacc'),
  ('Master Banque', 20, 'Licence'),
  ('Licence Art du spectacle', 17, 'Bacc'),
  ('Master Art du spectacle', 20, 'Licence'),
  ('Doctorat Art du spectacle', 3, 'Master'),
  ('Master Biotechnologie industrielle', 20, 'Licence'),
  ('Master Master en science', 20, 'Licence'),
  ('Master Technologie et production des bio ressources', 20, 'Licence'),
  ('Master Nutrition animale', 20, 'Licence'),
  ('Diplôme d\'Ingénieur Génie biomédical et maintenance des équipements médicaux', 19, 'Bac'),
  ('Diplôme d\'Ingénieur Génie mécanique et industriel', 19, 'Bac'),
  ('DIPES I Biologie', 16, 'Licence'),
  ('DIPES I Géologie', 16, 'Licence'),
  ('Licence Technologie des productions animales', 17, 'Bacc'),
  ('Licence Agrobusiness', 17, 'Bacc'),
  ('Licence Logistique et transport maritime', 17, 'Bacc'),
  ('Master Logistique et transport maritime', 20, 'Licence'),
  ('Licence Logistique et transit', 17, 'Bacc'),
  ('Master Logistique et transit', 20, 'Licence'),
  ('Licence Planification et conception de programmes', 17, 'Bacc'),
  ('Licence Leadership pédagogique', 17, 'Bacc'),
  ('Licence Psychologie communautaire', 17, 'Bacc'),
  ('Licence Éducation physique et animation', 17, 'Bacc'),
  ('Licence Études en communication et developpement', 17, 'Bacc'),
  ('Licence Littérature anglaise', 17, 'Bacc'),
  ('Master Littérature anglaise', 20, 'Licence'),
  ('Doctorat Littérature anglaise', 3, 'Master');
COMMIT;

START TRANSACTION;
INSERT IGNORE INTO diplomes (nom_dip, categorie_id, niveau) VALUES
  ('Licence Biotechnologie', 17, 'Bacc'),
  ('Master Biotechnologie médicale et pharmaceutique', 20, 'Licence'),
  ('Master Biotechnologie agricole', 20, 'Licence'),
  ('Master Biotechnologie nutritionnelle', 20, 'Licence'),
  ('Master Nutrition humaine', 20, 'Licence'),
  ('Diplôme d\'Ingénieur Génie des biotechnologies et des procédés alimentaires', 19, 'Bac'),
  ('DIPES I Lettres bilingues', 16, 'Licence'),
  ('DIPES I Chimie', 16, 'Licence'),
  ('Master Médecine et pharmacologie traditionnelle', 20, 'Licence'),
  ('Doctorat Médecine et pharmacologie traditionnelle', 3, 'Master'),
  ('DIPES II Chimie', 16, 'Master'),
  ('DIPES I Histoire', 16, 'Licence'),
  ('DIPES II Histoire', 16, 'Master'),
  ('DIPES I Lettres modernes anglaises', 16, 'Licence'),
  ('DIPES II Lettres modernes anglaises', 16, 'Master'),
  ('DIPES I Allemand', 16, 'Licence'),
  ('DIPES II Allemand', 16, 'Master'),
  ('DIPES I Arabe', 16, 'Licence'),
  ('DIPES II Arabe', 16, 'Master'),
  ('DIPES I Chinois', 16, 'Licence'),
  ('DIPES II Chinois', 16, 'Master'),
  ('DIPES I Mathématiques', 16, 'Licence'),
  ('DIPES II Mathématiques', 16, 'Master'),
  ('DIPES I Physiques', 16, 'Licence'),
  ('DIPES II Physiques', 16, 'Master'),
  ('DIPES I Philosophie', 16, 'Licence'),
  ('DIPES II Philosophie', 16, 'Master'),
  ('DIPCO Conseiller d\'orientation', 32, 'Bac'),
  ('Master Médecine et spécialités', 20, 'Licence'),
  ('Doctorat Médecine et spécialités', 3, 'Master'),
  ('DIPES I Géographie', 16, 'Licence'),
  ('DIPES II Géographie', 16, 'Master'),
  ('DIPES I Informatique', 16, 'Licence'),
  ('DIPES II Informatique', 16, 'Master'),
  ('DIPES I Lettres modernes françaises', 16, 'Licence'),
  ('DIPES II Lettres modernes françaises', 16, 'Master'),
  ('DIPES I Espagnol', 16, 'Licence'),
  ('DIPES II Espagnol', 16, 'Master'),
  ('DIPES I Italien', 16, 'Licence'),
  ('DIPES II Italien', 16, 'Master'),
  ('DIPES II Lettres bilingues', 16, 'Master'),
  ('DIPES II Biologie', 16, 'Master'),
  ('DIPES I Science de l\'éducation', 16, 'Licence'),
  ('DIPES II Science de l\'éducation', 16, 'Master'),
  ('DIPES I Lettres modernes', 16, 'Licence'),
  ('DIPES I Économie', 16, 'Licence'),
  ('DIPET I Électrotechnique', 16, 'Licence'),
  ('DIPET II Électrotechnique', 16, 'Master'),
  ('DIPET I Électronique', 16, 'Licence'),
  ('DIPET II Électronique', 16, 'Master');
COMMIT;

START TRANSACTION;
INSERT IGNORE INTO diplomes (nom_dip, categorie_id, niveau) VALUES
  ('DIPET I Économie sociale et familiale', 16, 'Licence'),
  ('DIPET II Économie sociale et familiale', 16, 'Master'),
  ('DIPET I Comptabilité', 16, 'Licence'),
  ('DIPET II Comptabilité', 16, 'Master'),
  ('DIPET I Gestion de l\'information et de la communication', 16, 'Licence'),
  ('DIPET II Gestion de l\'information et de la communication', 16, 'Master'),
  ('DIPET I Modèle d\'enseignement', 16, 'Licence'),
  ('DIPET II Modèle d\'enseignement', 16, 'Master'),
  ('DIPET I Fabrication mécanique', 16, 'Licence'),
  ('DIPET II Fabrication mécanique', 16, 'Master'),
  ('DIPET I Mode, habillement et textile', 16, 'Licence'),
  ('DIPET II Mode, habillement et textile', 16, 'Master'),
  ('Diplôme d\'Ingénieur de Travaux Génie civil et architecture', 32, 'Bac'),
  ('Diplôme d\'Ingénieur de Travaux Génie minéral et minier', 32, 'Bac'),
  ('Diplôme d\'Ingénieur de Travaux Ingénierie pétrolière', 32, 'Bac'),
  ('Diplôme d\'Ingénieur de Travaux Génie électrique', 32, 'Bac'),
  ('Diplôme d\'Ingénieur de Travaux Télécommunications', 32, 'Bac'),
  ('Diplôme d\'Ingénieur de Travaux Maintenance des réseaux et systèmes informatiques', 32, 'Bac'),
  ('Diplôme d\'Ingénieur de Travaux Data sciences', 32, 'Bac'),
  ('DIPES I Physique', 16, 'Licence'),
  ('DIPES II Conseil et orientation', 16, 'Master'),
  ('DIPES II Sciences de l\'éducation', 16, 'Master'),
  ('DIPET I Mécanique automobile', 16, 'Licence'),
  ('DIPET II Mécanique automobile', 16, 'Master'),
  ('DIPET I Informatique', 16, 'Licence'),
  ('DIPET II Informatique', 16, 'Master'),
  ('DIPET I Climatisation et réfrigération', 16, 'Licence'),
  ('DIPET II Climatisation et réfrigération', 16, 'Master'),
  ('DIPET I Marketing', 16, 'Licence'),
  ('DIPET II Marketing', 16, 'Master'),
  ('DIPET I Bâtiment et travaux publics', 16, 'Licence'),
  ('DIPET II Bâtiment et travaux publics', 16, 'Master'),
  ('DIPET I Conception mécanique', 16, 'Licence'),
  ('DIPET II Conception mécanique', 16, 'Master'),
  ('DIPET I Sciences de l\'éducation', 16, 'Licence'),
  ('DIPET II Sciences de l\'éducation', 16, 'Master'),
  ('DIPET II Droit', 16, 'Master'),
  ('Diplôme d\'Ingénieur de Travaux Ingénierie informatique', 32, 'Bac'),
  ('Diplôme d\'Ingénieur de Travaux Électronique', 32, 'Bac'),
  ('Diplôme d\'Ingénieur de Travaux Énergies renouvelables', 32, 'Bac'),
  ('Diplôme d\'Ingénieur de Travaux Génie logiciel', 32, 'Bac'),
  ('DIPET I Travail du bois', 16, 'Licence'),
  ('DIPET II Travail du bois', 16, 'Master'),
  ('DIPET II Technologies de l\'information et de la communication', 16, 'Master'),
  ('DIPET II Construction de bâtiments', 16, 'Master'),
  ('DIPET II Agriculture', 16, 'Master'),
  ('DUT Génie logistique et transport (GLT)', 12, 'Bacc'),
  ('Licence Pro Génie logistique et transport (GLT)', 18, 'Bacc'),
  ('DUT Gestion appliquée aux petites et moyennes organisation', 12, 'Bacc'),
  ('Master Biologie des organismes animaux', 20, 'Licence');
COMMIT;

START TRANSACTION;
INSERT IGNORE INTO diplomes (nom_dip, categorie_id, niveau) VALUES
  ('Doctorat Biologie des organismes animaux', 3, 'Master'),
  ('Licence Sciences environnementales', 17, 'Bacc'),
  ('Master Sciences environnementales', 20, 'Licence'),
  ('Doctorat Sciences environnementales', 3, 'Master'),
  ('Licence Sciences géologiques et minières', 17, 'Bacc'),
  ('Master Sciences géologiques et minières', 20, 'Licence'),
  ('Doctorat Sciences géologiques et minières', 3, 'Master'),
  ('Licence Sciences géodésiques', 17, 'Bacc'),
  ('Master Sciences géodésiques', 20, 'Licence'),
  ('Doctorat Sciences géodésiques', 3, 'Master'),
  ('Licence Analyse et politique economique', 17, 'Bacc'),
  ('Master Analyse et politique economique', 20, 'Licence'),
  ('Doctorat Analyse et politique economique', 3, 'Master'),
  ('Licence Économie de l´environnement', 17, 'Bacc'),
  ('Master Économie de l´environnement', 20, 'Licence'),
  ('Doctorat Économie de l´environnement', 3, 'Master'),
  ('Licence Techniques quantitatives', 17, 'Bacc'),
  ('Master Techniques quantitatives', 20, 'Licence'),
  ('Doctorat Techniques quantitatives', 3, 'Master'),
  ('Licence Contrôle et comptabilité', 17, 'Bacc'),
  ('Master Contrôle et comptabilité', 20, 'Licence'),
  ('Doctorat Contrôle et comptabilité', 3, 'Master'),
  ('Licence Marketing et stratégie', 17, 'Bacc'),
  ('Master Marketing et stratégie', 20, 'Licence'),
  ('Doctorat Marketing et stratégie', 3, 'Master'),
  ('Licence Théorie du Droit, d´Epistémologie et de Droit Comparé', 17, 'Bacc'),
  ('Master Théorie du Droit, d´Epistémologie et de Droit Comparé', 20, 'Licence'),
  ('Doctorat Théorie du Droit, d´Epistémologie et de Droit Comparé', 3, 'Master'),
  ('Licence Arts du spectacle', 17, 'Bacc'),
  ('Master Arts du spectacle', 20, 'Licence'),
  ('Doctorat Arts du spectacle', 3, 'Master'),
  ('Diplôme d\'Ingénieur Génie sanitaire et environnement', 19, 'Bac'),
  ('Diplôme d\'Ingénieur Génie logiciel', 19, 'Bac'),
  ('Diplôme d\'Ingénieur Sécurité', 19, 'Bac'),
  ('Diplôme d\'Ingénieur Dépollution', 19, 'Bac'),
  ('Diplôme d\'Ingénieur Population et résolution des conflits', 19, 'Bac'),
  ('Doctorat Génie informatique et télécommunications', 3, 'Master'),
  ('Doctorat Génie énergétique', 3, 'Master'),
  ('Doctorat Génie hydraulique et mécanique', 3, 'Master'),
  ('Licence Biologie des organismes végétaux', 17, 'Bacc'),
  ('Master Biologie des organismes végétaux', 20, 'Licence'),
  ('Doctorat Biologie des organismes végétaux', 3, 'Master'),
  ('Licence Volcanique', 17, 'Bacc'),
  ('Master Volcanique', 20, 'Licence'),
  ('Doctorat Volcanique', 3, 'Master'),
  ('Licence Économie agricole et des changements climatiques', 17, 'Bacc'),
  ('Master Économie agricole et des changements climatiques', 20, 'Licence'),
  ('Doctorat Économie agricole et des changements climatiques', 3, 'Master'),
  ('Licence Économie publique', 17, 'Bacc'),
  ('Master Économie publique', 20, 'Licence');
COMMIT;

START TRANSACTION;
INSERT IGNORE INTO diplomes (nom_dip, categorie_id, niveau) VALUES
  ('Doctorat Économie publique', 3, 'Master'),
  ('Licence Gestion des ressources humaines', 17, 'Bacc'),
  ('Master Gestion des ressources humaines', 20, 'Licence'),
  ('Licence Finance', 17, 'Bacc'),
  ('Master Finance', 20, 'Licence'),
  ('Doctorat Finance', 3, 'Master'),
  ('Licence Droit Privé', 17, 'Bacc'),
  ('Master Droit Privé', 20, 'Licence'),
  ('Doctorat Droit Privé', 3, 'Master'),
  ('Licence Anthropologie', 17, 'Bacc'),
  ('Master Anthropologie', 20, 'Licence'),
  ('Doctorat Anthropologie', 3, 'Master'),
  ('Licence Beaux Arts', 17, 'Bacc'),
  ('Master Beaux Arts', 20, 'Licence'),
  ('Doctorat Beaux Arts', 3, 'Master'),
  ('Diplôme d\'Ingénieur Génie hydraulique', 19, 'Bac'),
  ('Diplôme d\'Ingénieur Réseaux', 19, 'Bac'),
  ('Diplôme d\'Ingénieur Désertification', 19, 'Bac'),
  ('Diplôme d\'Ingénieur Gestion des organisations et des entreprises de développement', 19, 'Bac'),
  ('Diplôme d\'Ingénieur Gestion administrative des réformes et de la décentralisation', 19, 'Bac'),
  ('Doctorat Biologie appliquée et agronomie', 3, 'Master'),
  ('Doctorat Chimie appliquée', 3, 'Master'),
  ('Doctorat Arts plastiques et photographie', 3, 'Master'),
  ('Doctorat Images numériques', 3, 'Master'),
  ('Doctorat Théâtre et danse', 3, 'Master'),
  ('Diplôme d\'Ingénieur de Travaux Production végétale', 32, 'Bac'),
  ('Diplôme d\'Ingénieur Production végétale', 19, 'Bac'),
  ('Diplôme d\'Ingénieur de Travaux Economie agricole et management des entreprises agricoles', 32, 'Bac'),
  ('Diplôme d\'Ingénieur Economie agricole et management des entreprises agricoles', 19, 'Bac'),
  ('Diplôme d\'Ingénieur de Travaux Beaux-arts', 32, 'Bac'),
  ('Diplôme d\'Ingénieur Beaux-arts', 19, 'Bac'),
  ('Diplôme d\'Ingénieur de Travaux Biomasse', 32, 'Bac'),
  ('Diplôme d\'Ingénieur Biomasse', 19, 'Bac'),
  ('Diplôme d\'Ingénieur de Travaux Fibre et textile', 32, 'Bac'),
  ('Diplôme d\'Ingénieur Fibre et textile', 19, 'Bac'),
  ('Diplôme d\'Ingénieur de Travaux Technologie du textile', 32, 'Bac'),
  ('Diplôme d\'Ingénieur Technologie du textile', 19, 'Bac'),
  ('Diplôme d\'Ingénieur de Travaux Sécurité et administration réseau', 32, 'Bac'),
  ('Diplôme d\'Ingénieur de Travaux Informatique de gestion', 32, 'Bac'),
  ('Diplôme d\'Ingénieur de Travaux Génie environnement', 32, 'Bac'),
  ('Diplôme d\'Ingénieur de Travaux Architecture et habitat', 32, 'Bac'),
  ('Diplôme d\'Ingénieur de Travaux Exploration pétrolière et gazière', 32, 'Bac'),
  ('Diplôme d\'Ingénieur Exploration pétrolière et gazière', 19, 'Bac'),
  ('Diplôme d\'Ingénieur de Travaux Raffinage et pétrochimie', 32, 'Bac'),
  ('Diplôme d\'Ingénieur de Travaux Transport et stockage du pétrole et du gaz', 32, 'Bac'),
  ('Diplôme d\'Ingénieur Transport et stockage du pétrole et du gaz', 19, 'Bac'),
  ('Diplôme d\'Ingénieur de Travaux Economie et de gestion du pétrole et du gaz', 32, 'Bac'),
  ('Diplôme d\'Ingénieur Economie et de gestion du pétrole et du gaz', 19, 'Bac'),
  ('Licence Pro Traduction', 18, 'Bacc'),
  ('Master Pro Traduction', 22, 'Licence');
COMMIT;

START TRANSACTION;
INSERT IGNORE INTO diplomes (nom_dip, categorie_id, niveau) VALUES
  ('Doctorat Mathématiques et physique', 3, 'Master'),
  ('Doctorat Cinéma et audiovisuel', 3, 'Master'),
  ('Doctorat Musique', 3, 'Master'),
  ('Diplôme d\'Ingénieur de Travaux Agro-alimentaire', 32, 'Bac'),
  ('Diplôme d\'Ingénieur Agro-alimentaire', 19, 'Bac'),
  ('Diplôme d\'Ingénieur de Travaux Production animale-aquaculture', 32, 'Bac'),
  ('Diplôme d\'Ingénieur Production animale-aquaculture', 19, 'Bac'),
  ('Diplôme d\'Ingénieur de Travaux Stylisme et modélisme', 32, 'Bac'),
  ('Diplôme d\'Ingénieur Stylisme et modélisme', 19, 'Bac'),
  ('Diplôme d\'Ingénieur de Travaux Sciences du patrimoine', 32, 'Bac'),
  ('Diplôme d\'Ingénieur Sciences du patrimoine', 19, 'Bac'),
  ('Diplôme d\'Ingénieur de Travaux Eolien', 32, 'Bac'),
  ('Diplôme d\'Ingénieur Eolien', 19, 'Bac'),
  ('Diplôme d\'Ingénieur de Travaux Cuir', 32, 'Bac'),
  ('Diplôme d\'Ingénieur de Travaux Hydraulique et maîtrise des eaux', 32, 'Bac'),
  ('Diplôme d\'Ingénieur Télécommunications', 19, 'Bac'),
  ('Diplôme d\'Ingénieur de Travaux Education environnementale', 32, 'Bac'),
  ('Diplôme d\'Ingénieur de Travaux Matériaux', 32, 'Bac'),
  ('Diplôme d\'Ingénieur de Travaux Mines et carrières', 32, 'Bac'),
  ('Diplôme d\'Ingénieur Mines et carrières', 19, 'Bac'),
  ('Diplôme d\'Ingénieur de Travaux Production pétrolière et gazière', 32, 'Bac'),
  ('Diplôme d\'Ingénieur Production pétrolière et gazière', 19, 'Bac'),
  ('Diplôme d\'Ingénieur de Travaux Génie mécanique et electrique', 32, 'Bac'),
  ('Diplôme d\'Ingénieur Génie mécanique et electrique', 19, 'Bac'),
  ('Diplôme d\'Ingénieur de Travaux Sécurité industrielle, qualité et environnement', 32, 'Bac'),
  ('Diplôme d\'Ingénieur Sécurité industrielle, qualité et environnement', 19, 'Bac'),
  ('Licence Pro Psychopédagogie et éducation spécialisée', 18, 'Bacc'),
  ('Master Pro Psychopédagogie et éducation spécialisée', 22, 'Licence'),
  ('DUT Génie informatique', 12, 'Bacc'),
  ('DUT Génie biomédical (GBM)', 12, 'Bacc'),
  ('DUT Génie mécanique et productique (GMP)', 12, 'Bacc'),
  ('DUT Génie ferroviaire (GFE)', 12, 'Bacc'),
  ('DUT Génie métallurgique ( GME)', 12, 'Bacc'),
  ('DUT Biotechnologie et technologie alimentaire', 12, 'Bacc'),
  ('Licence Droit privé général et sciences criminelles', 17, 'Bacc'),
  ('Licence Droit d\'inspiration «commun law»', 17, 'Bacc'),
  ('Master Droit d\'inspiration «commun law»', 20, 'Licence'),
  ('Doctorat Droit d\'inspiration «commun law»', 3, 'Master'),
  ('Licence Cadres d\'administration', 17, 'Bacc'),
  ('Licence Sciences économiques', 17, 'Bacc'),
  ('Licence Biologie moléculaire et cellulaire', 17, 'Bacc'),
  ('Master Biologie moléculaire et cellulaire', 20, 'Licence'),
  ('Doctorat Biologie moléculaire et cellulaire', 3, 'Master'),
  ('Licence Bio-informatique et bio statistique', 17, 'Bacc'),
  ('Master Bio-informatique et bio statistique', 20, 'Licence'),
  ('Doctorat Bio-informatique et bio statistique', 3, 'Master'),
  ('Licence Biologie des organismes vivants', 17, 'Bacc'),
  ('Master Biologie des organismes vivants', 20, 'Licence'),
  ('Doctorat Biologie des organismes vivants', 3, 'Master'),
  ('Licence Physique et application', 17, 'Bacc');
COMMIT;

START TRANSACTION;
INSERT IGNORE INTO diplomes (nom_dip, categorie_id, niveau) VALUES
  ('Master Physique et application', 20, 'Licence'),
  ('Doctorat Physique et application', 3, 'Master'),
  ('Licence Physique et mécanique', 17, 'Bacc'),
  ('Master Physique et mécanique', 20, 'Licence'),
  ('Doctorat Physique et mécanique', 3, 'Master'),
  ('Master Physique fondamentale', 20, 'Licence'),
  ('Doctorat Physique fondamentale', 3, 'Master'),
  ('Licence Physique-chimie', 17, 'Bacc'),
  ('Master Physique-chimie', 20, 'Licence'),
  ('Doctorat Physique-chimie', 3, 'Master'),
  ('Licence Chimie et biologie', 17, 'Bacc'),
  ('Master Chimie et biologie', 20, 'Licence'),
  ('Doctorat Chimie et biologie', 3, 'Master'),
  ('Licence Géosciences', 17, 'Bacc'),
  ('Master Géosciences', 20, 'Licence'),
  ('Doctorat Géosciences', 3, 'Master'),
  ('Licence Algèbre, analyse et géometrie', 17, 'Bacc'),
  ('Master Algèbre, analyse et géometrie', 20, 'Licence'),
  ('DUT Génie électrique et informatique industrielle (GEII)', 12, 'Bacc'),
  ('DUT Génie industriel et maintenance (GIM)', 12, 'Bacc'),
  ('DUT Génie thermique et énergie (GTE)', 12, 'Bacc'),
  ('DUT Génie des mines (GMI)', 12, 'Bacc'),
  ('DUT Génie civil', 12, 'Bacc'),
  ('Licence Droit des affaires', 17, 'Bacc'),
  ('Doctorat Droit des affaires', 3, 'Master'),
  ('Licence Carrières judiciaires', 17, 'Bacc'),
  ('Licence Sciences de gestion', 17, 'Bacc'),
  ('Licence Biologie humaine et santé', 17, 'Bacc'),
  ('Master Biologie humaine et santé', 20, 'Licence'),
  ('Doctorat Biologie humaine et santé', 3, 'Master'),
  ('Master Biochimie', 20, 'Licence'),
  ('Doctorat Biochimie', 3, 'Master'),
  ('Licence Chimie physique', 17, 'Bacc'),
  ('Master Chimie physique', 20, 'Licence'),
  ('Doctorat Chimie physique', 3, 'Master'),
  ('BTS Climatologie', 5, 'Bac'),
  ('Diplôme d\'Ingénieur Climatologie', 19, 'Bac'),
  ('BTS Hydrologie', 5, 'Bac'),
  ('Diplôme d\'Ingénieur Hydrologie', 19, 'Bac'),
  ('Licence Histoire', 17, 'Bacc'),
  ('Master Histoire', 20, 'Licence'),
  ('Doctorat Histoire', 3, 'Master'),
  ('Licence Lettres bilingues', 17, 'Bacc'),
  ('Master Lettres bilingues', 20, 'Licence'),
  ('Doctorat Lettres bilingues', 3, 'Master'),
  ('Licence Lettres modernes françaises', 17, 'Bacc'),
  ('Master Lettres modernes françaises', 20, 'Licence'),
  ('Doctorat Lettres modernes françaises', 3, 'Master'),
  ('Licence Arabe', 17, 'Bacc'),
  ('Master Arabe', 20, 'Licence');
COMMIT;

START TRANSACTION;
INSERT IGNORE INTO diplomes (nom_dip, categorie_id, niveau) VALUES
  ('Doctorat Arabe', 3, 'Master'),
  ('Licence Espagnol', 17, 'Bacc'),
  ('Master Espagnol', 20, 'Licence'),
  ('Doctorat Espagnol', 3, 'Master'),
  ('Licence Chimie des substances naturelles', 17, 'Bacc'),
  ('Master Chimie des substances naturelles', 20, 'Licence'),
  ('Doctorat Chimie des substances naturelles', 3, 'Master'),
  ('Licence Chimie de l´eau', 17, 'Bacc'),
  ('Master Chimie de l´eau', 20, 'Licence'),
  ('Doctorat Chimie de l´eau', 3, 'Master'),
  ('Licence Informatique et gestion', 17, 'Bacc'),
  ('Master Informatique et gestion', 20, 'Licence'),
  ('Doctorat Informatique et gestion', 3, 'Master'),
  ('Licence Mathématiques appliquées', 17, 'Bacc'),
  ('Master Mathématiques appliquées', 20, 'Licence'),
  ('Doctorat Mathématiques appliquées', 3, 'Master'),
  ('Licence Didactiques  mathématiques', 17, 'Bacc'),
  ('Master Didactiques  mathématiques', 20, 'Licence'),
  ('Doctorat Didactiques  mathématiques', 3, 'Master'),
  ('Licence Électronique', 17, 'Bacc'),
  ('Master Électronique', 20, 'Licence'),
  ('Doctorat Électronique', 3, 'Master'),
  ('Licence Énergies renouvelables', 17, 'Bacc'),
  ('Master Énergies renouvelables', 20, 'Licence'),
  ('Doctorat Énergies renouvelables', 3, 'Master'),
  ('Licence Physique et applications', 17, 'Bacc'),
  ('Master Physique et applications', 20, 'Licence'),
  ('Doctorat Physique et applications', 3, 'Master'),
  ('BTS Pédologie', 5, 'Bac'),
  ('Diplôme d\'Ingénieur Pédologie', 19, 'Bac'),
  ('Licence Géographie', 17, 'Bacc'),
  ('Master Géographie', 20, 'Licence'),
  ('Doctorat Géographie', 3, 'Master'),
  ('Licence Lettres modernes anglaises', 17, 'Bacc'),
  ('Master Lettres modernes anglaises', 20, 'Licence'),
  ('Doctorat Lettres modernes anglaises', 3, 'Master'),
  ('Licence Sociologie', 17, 'Bacc'),
  ('Master Sociologie', 20, 'Licence'),
  ('Doctorat Sociologie', 3, 'Master'),
  ('Licence Psychologie', 17, 'Bacc'),
  ('Master Psychologie', 20, 'Licence'),
  ('Doctorat Psychologie', 3, 'Master'),
  ('Licence Allemand', 17, 'Bacc'),
  ('Master Allemand', 20, 'Licence'),
  ('Doctorat Allemand', 3, 'Master'),
  ('Licence Chinois', 17, 'Bacc'),
  ('Master Chinois', 20, 'Licence'),
  ('Doctorat Chinois', 3, 'Master'),
  ('Licence Chimie de l´environnement', 17, 'Bacc'),
  ('Master Chimie de l´environnement', 20, 'Licence');
COMMIT;

START TRANSACTION;
INSERT IGNORE INTO diplomes (nom_dip, categorie_id, niveau) VALUES
  ('Doctorat Chimie de l´environnement', 3, 'Master'),
  ('Licence Chimie industrielle', 17, 'Bacc'),
  ('Master Chimie industrielle', 20, 'Licence'),
  ('Doctorat Chimie industrielle', 3, 'Master'),
  ('Licence Architecture et réseaux', 17, 'Bacc'),
  ('Master Architecture et réseaux', 20, 'Licence'),
  ('Doctorat Architecture et réseaux', 3, 'Master'),
  ('Licence Informatique fondamentale', 17, 'Bacc'),
  ('Master Informatique fondamentale', 20, 'Licence'),
  ('Doctorat Informatique fondamentale', 3, 'Master'),
  ('Licence Mathématiques pures', 17, 'Bacc'),
  ('Master Mathématiques pures', 20, 'Licence'),
  ('Doctorat Mathématiques pures', 3, 'Master'),
  ('Master Pro Gestion de service alimentaire', 22, 'Licence'),
  ('Licence Sécurité et sûreté industrielle', 17, 'Bacc'),
  ('Master Sécurité et sûreté industrielle', 20, 'Licence'),
  ('Licence Qualité et normalisation', 17, 'Bacc'),
  ('Master Qualité et normalisation', 20, 'Licence'),
  ('Licence Moteur et transmission de puissance', 17, 'Bacc'),
  ('Master Moteur et transmission de puissance', 20, 'Licence'),
  ('Licence Technologie de l´environnement et maîtrise de l´énergie', 17, 'Bacc'),
  ('Master Technologie de l´environnement et maîtrise de l´énergie', 20, 'Licence'),
  ('Licence Systèmes intelligents, vision et robotique', 17, 'Bacc'),
  ('Master Systèmes intelligents, vision et robotique', 20, 'Licence'),
  ('Master Sciences biologiques spécialité biochimie', 20, 'Licence'),
  ('Doctorat Sciences biologiques spécialité biochimie', 3, 'Master'),
  ('Master Sciences biologiques spécialité biologie animale', 20, 'Licence'),
  ('Doctorat Sciences biologiques spécialité biologie animale', 3, 'Master'),
  ('Master Sciences biologiques spécialité chimie organique', 20, 'Licence'),
  ('Doctorat Sciences biologiques spécialité chimie organique', 3, 'Master'),
  ('Master Sciences biologiques spécialité hématologie', 20, 'Licence'),
  ('Doctorat Sciences biologiques spécialité hématologie', 3, 'Master'),
  ('Master Sciences biologiques spécialité immunologie', 20, 'Licence'),
  ('Doctorat Sciences biologiques spécialité immunologie', 3, 'Master'),
  ('Master Sciences biologiques spécialité mycologie', 20, 'Licence'),
  ('Doctorat Sciences biologiques spécialité mycologie', 3, 'Master'),
  ('Master Sciences biologiques spécialité physiologie', 20, 'Licence'),
  ('Doctorat Sciences biologiques spécialité physiologie', 3, 'Master'),
  ('Master Droit privé fondamental', 20, 'Licence'),
  ('Doctorat Droit privé fondamental', 3, 'Master'),
  ('Master Économétrie et politiques conjoncturelles', 20, 'Licence'),
  ('Master Macroéconomie ouverte', 20, 'Licence'),
  ('Master Finance d\'entreprise', 20, 'Licence'),
  ('Licence Environnement industriel', 17, 'Bacc'),
  ('Master Environnement industriel', 20, 'Licence'),
  ('Licence Carrosseries et suspensions', 17, 'Bacc'),
  ('Master Carrosseries et suspensions', 20, 'Licence'),
  ('Licence Mécatronique', 17, 'Bacc'),
  ('Master Mécatronique', 20, 'Licence'),
  ('Licence Automatisation et contrôles des systèmes industriels', 17, 'Bacc');
COMMIT;

START TRANSACTION;
INSERT IGNORE INTO diplomes (nom_dip, categorie_id, niveau) VALUES
  ('Master Automatisation et contrôles des systèmes industriels', 20, 'Licence'),
  ('Master Sciences biologiques spécialité bactériologie', 20, 'Licence'),
  ('Doctorat Sciences biologiques spécialité bactériologie', 3, 'Master'),
  ('Master Sciences biologiques spécialité biologie moléculaire', 20, 'Licence'),
  ('Doctorat Sciences biologiques spécialité biologie moléculaire', 3, 'Master'),
  ('Master Sciences biologiques spécialité chimie minérale', 20, 'Licence'),
  ('Doctorat Sciences biologiques spécialité chimie minérale', 3, 'Master'),
  ('Master Sciences biologiques spécialité endocrinologie', 20, 'Licence'),
  ('Doctorat Sciences biologiques spécialité endocrinologie', 3, 'Master'),
  ('Master Sciences biologiques spécialité hématologie clinique', 20, 'Licence'),
  ('Doctorat Sciences biologiques spécialité hématologie clinique', 3, 'Master'),
  ('Master Sciences biologiques spécialité histologie', 20, 'Licence'),
  ('Doctorat Sciences biologiques spécialité histologie', 3, 'Master'),
  ('Master Sciences biologiques spécialité microbiologie', 20, 'Licence'),
  ('Doctorat Sciences biologiques spécialité microbiologie', 3, 'Master'),
  ('Master Sciences biologiques spécialité parasitologie', 20, 'Licence'),
  ('Doctorat Sciences biologiques spécialité parasitologie', 3, 'Master'),
  ('Master Méthodes informatiques appliquées à la gestion d\'entreprise', 20, 'Licence'),
  ('Master Économie monétaire et bancaire', 20, 'Licence'),
  ('Master Économie publique et économie industrielle', 20, 'Licence'),
  ('Master Comptabilité, audit et contrôle', 20, 'Licence'),
  ('Master Marketing, stratégie organisation', 20, 'Licence'),
  ('Licence Économie et mahématiques', 17, 'Bacc'),
  ('Master Économie et mahématiques', 20, 'Licence'),
  ('Licence Informatique', 17, 'Bacc'),
  ('Master Informatique', 20, 'Licence'),
  ('Licence Anglais', 17, 'Bacc'),
  ('Master Anglais', 20, 'Licence'),
  ('Doctorat Anglais', 3, 'Master'),
  ('Licence Français et études francophones spécialité littérature', 17, 'Bacc'),
  ('Licence Littérature négro-africaine', 17, 'Bacc'),
  ('Master Littérature négro-africaine', 20, 'Licence'),
  ('Doctorat Littérature négro-africaine', 3, 'Master'),
  ('Licence Anthropologie politique', 17, 'Bacc'),
  ('Master Anthropologie politique', 20, 'Licence'),
  ('Doctorat Anthropologie politique', 3, 'Master'),
  ('Licence Communication politique', 17, 'Bacc'),
  ('Master Communication politique', 20, 'Licence'),
  ('Doctorat Communication politique', 3, 'Master'),
  ('Licence Géographie physique et environnement', 17, 'Bacc'),
  ('Master Géographie physique et environnement', 20, 'Licence'),
  ('Doctorat Géographie physique et environnement', 3, 'Master'),
  ('Licence Histoire économique', 17, 'Bacc'),
  ('Master Histoire économique', 20, 'Licence'),
  ('Doctorat Histoire économique', 3, 'Master'),
  ('Licence Philosophie des sciences', 17, 'Bacc'),
  ('Master Philosophie des sciences', 20, 'Licence'),
  ('Doctorat Philosophie des sciences', 3, 'Master'),
  ('Licence Éthique et politique', 17, 'Bacc'),
  ('Doctorat Éthique et politique', 3, 'Master');
COMMIT;

START TRANSACTION;
INSERT IGNORE INTO diplomes (nom_dip, categorie_id, niveau) VALUES
  ('Licence Psychopathologie de l\'enfant', 17, 'Bacc'),
  ('Master Psychopathologie de l\'enfant', 20, 'Licence'),
  ('Doctorat Psychopathologie de l\'enfant', 3, 'Master'),
  ('Licence Égyptologie', 17, 'Bacc'),
  ('Master Égyptologie', 20, 'Licence'),
  ('Doctorat Égyptologie', 3, 'Master'),
  ('Licence Fabrication mécanique et productique', 17, 'Bacc'),
  ('Master Fabrication mécanique et productique', 20, 'Licence'),
  ('Licence Génie informatique', 17, 'Bacc'),
  ('Master Génie informatique', 20, 'Licence'),
  ('Licence Ingénieur radio & tv', 17, 'Bacc'),
  ('Master Ingénieur radio & tv', 20, 'Licence'),
  ('Licence Voies et ouvrages d´art', 17, 'Bacc'),
  ('Master Voies et ouvrages d´art', 20, 'Licence'),
  ('Licence Construction navale', 17, 'Bacc'),
  ('Master Construction navale', 20, 'Licence'),
  ('Licence Patron de pêche', 17, 'Bacc'),
  ('Master Patron de pêche', 20, 'Licence'),
  ('Licence Mathématique et informatiques', 17, 'Bacc'),
  ('Master Mathématique et informatiques', 20, 'Licence'),
  ('Licence Français et études francophones spécialité langue', 17, 'Bacc'),
  ('Master Français et études francophones spécialité langue', 20, 'Licence'),
  ('Doctorat Français et études francophones spécialité langue', 3, 'Master'),
  ('Doctorat Langues africaines et linguistique', 3, 'Master'),
  ('Licence Anthropologie médicale', 17, 'Bacc'),
  ('Master Anthropologie médicale', 20, 'Licence'),
  ('Doctorat Anthropologie médicale', 3, 'Master'),
  ('Licence Communication sociale', 17, 'Bacc'),
  ('Master Communication sociale', 20, 'Licence'),
  ('Doctorat Communication sociale', 3, 'Master'),
  ('Licence Communication des organisations', 17, 'Bacc'),
  ('Master Communication des organisations', 20, 'Licence'),
  ('Licence Géographie humaine et aménagement', 17, 'Bacc'),
  ('Master Géographie humaine et aménagement', 20, 'Licence'),
  ('Doctorat Géographie humaine et aménagement', 3, 'Master'),
  ('Licence Histoire politique et relations internationales', 17, 'Bacc'),
  ('Master Histoire politique et relations internationales', 20, 'Licence'),
  ('Doctorat Histoire politique et relations internationales', 3, 'Master'),
  ('Licence Histoire de la philosophie', 17, 'Bacc'),
  ('Doctorat Histoire de la philosophie', 3, 'Master'),
  ('Licence Psychologie sociale', 17, 'Bacc'),
  ('Master Psychologie sociale', 20, 'Licence'),
  ('Doctorat Psychologie sociale', 3, 'Master'),
  ('Licence Sociologie politique et économique', 17, 'Bacc'),
  ('Master Sociologie politique et économique', 20, 'Licence'),
  ('Doctorat Sociologie politique et économique', 3, 'Master'),
  ('Licence Construction mécanique', 17, 'Bacc'),
  ('Master Construction mécanique', 20, 'Licence'),
  ('Licence Construction industrielle', 17, 'Bacc'),
  ('Master Construction industrielle', 20, 'Licence');
COMMIT;

START TRANSACTION;
INSERT IGNORE INTO diplomes (nom_dip, categorie_id, niveau) VALUES
  ('Licence Ingénieur télécoms', 17, 'Bacc'),
  ('Master Ingénieur télécoms', 20, 'Licence'),
  ('Licence Construction civile et industrielle', 17, 'Bacc'),
  ('Master Construction civile et industrielle', 20, 'Licence'),
  ('Licence Ouvrages hydrauliques', 17, 'Bacc'),
  ('Master Ouvrages hydrauliques', 20, 'Licence'),
  ('Licence Génie mécanique naval', 17, 'Bacc'),
  ('Master Génie mécanique naval', 20, 'Licence'),
  ('Licence Pro Évaluation et gestion des risques et catastrophes', 18, 'Bacc'),
  ('Master Pro Évaluation et gestion des risques et catastrophes', 22, 'Licence'),
  ('Licence Pro Gouvernance publique', 18, 'Bacc'),
  ('Master Pro Gouvernance publique', 22, 'Licence'),
  ('Licence Pro Gouvernance financière', 18, 'Bacc'),
  ('Master Pro Gouvernance financière', 22, 'Licence'),
  ('Licence Pro Juristes d´entreprise', 18, 'Bacc'),
  ('Master Pro Juristes d´entreprise', 22, 'Licence'),
  ('Licence Pro Comptabilité', 18, 'Bacc'),
  ('Licence Pro Entrepreneuriat, création d´entreprises et management des PME/PMI', 18, 'Bacc'),
  ('Licence Pro Conseil Juridique et Fiscal', 18, 'Bacc'),
  ('Master Pro Conseil Juridique et Fiscal', 22, 'Licence'),
  ('Licence Pro Gouvernance administrative', 18, 'Bacc'),
  ('Master Pro Gouvernance administrative', 22, 'Licence'),
  ('Licence Pro Droit et pratique des professions juridiques et judiciaires', 18, 'Bacc'),
  ('Master Pro Droit et pratique des professions juridiques et judiciaires', 22, 'Licence'),
  ('DUT Génie civil bois', 12, 'Bacc'),
  ('Licence Génie civil bois', 17, 'Bacc'),
  ('Master Génie civil bois', 20, 'Licence'),
  ('DUT Chimie du bois', 12, 'Bacc'),
  ('Diplôme d\'Ingénieur de Travaux Chimie du bois', 32, 'Bac'),
  ('DUT Sciences du papier et bioénergie', 12, 'Bacc'),
  ('Diplôme d\'Ingénieur de Travaux Sciences du papier et bioénergie', 32, 'Bac'),
  ('DUT Électronique', 12, 'Bacc'),
  ('BTS Secrétariat de direction', 5, 'Bac'),
  ('DUT Génie des télécommunications et réseaux', 12, 'Bacc'),
  ('Licence Génie informatique et réseaux', 17, 'Bacc'),
  ('Licence Gynécologie obstétrique', 17, 'Bacc'),
  ('Master Gynécologie obstétrique', 20, 'Licence'),
  ('Doctorat Gynécologie obstétrique', 3, 'Master'),
  ('Licence Pharmacie et pharmacopée africaine', 17, 'Bacc'),
  ('Master Pharmacie et pharmacopée africaine', 20, 'Licence'),
  ('Doctorat Pharmacie et pharmacopée africaine', 3, 'Master'),
  ('Licence Soins infirmiers', 17, 'Bacc'),
  ('Master Soins infirmiers', 20, 'Licence'),
  ('Doctorat Soins infirmiers', 3, 'Master'),
  ('DUT Électrotechnique', 12, 'Bacc'),
  ('BTS Aménagement urbain ou travaux publics.', 5, 'Bac'),
  ('DUT Informatique de gestion', 12, 'Bacc'),
  ('DUT Génie mécanique et productique', 12, 'Bacc'),
  ('Licence Génie electrique', 17, 'Bacc'),
  ('Licence Radiologie et imagérie médicale', 17, 'Bacc');
COMMIT;

START TRANSACTION;
INSERT IGNORE INTO diplomes (nom_dip, categorie_id, niveau) VALUES
  ('Master Radiologie et imagérie médicale', 20, 'Licence'),
  ('Doctorat Radiologie et imagérie médicale', 3, 'Master'),
  ('Licence Sciences de laboratoire', 17, 'Bacc'),
  ('Master Sciences de laboratoire', 20, 'Licence'),
  ('Doctorat Sciences de laboratoire', 3, 'Master'),
  ('Doctorat Analyse et politique économique', 3, 'Master'),
  ('Doctorat Macroéconomie ouverte et finance internationale', 3, 'Master'),
  ('Doctorat Politique économique et développement', 3, 'Master'),
  ('Doctorat Marketing, stratégie organisation', 3, 'Master'),
  ('Doctorat Physique atomique moléculaire et optique quantitat', 3, 'Master'),
  ('DIPET I Installation sanitaire', 16, 'Licence'),
  ('DIPET II Installation sanitaire', 16, 'Master'),
  ('Doctorat Installation sanitaire', 3, 'Master'),
  ('DIPET I Froid et climatisation', 16, 'Licence'),
  ('DIPET II Froid et climatisation', 16, 'Master'),
  ('Doctorat Froid et climatisation', 3, 'Master'),
  ('Doctorat Fabrication mécanique', 3, 'Master'),
  ('DIPET I Métier du bois', 16, 'Licence'),
  ('DIPET II Métier du bois', 16, 'Master'),
  ('Doctorat Métier du bois', 3, 'Master'),
  ('DIPET I Industrie de l\'habillement', 16, 'Licence'),
  ('DIPET II Industrie de l\'habillement', 16, 'Master'),
  ('Doctorat Industrie de l\'habillement', 3, 'Master'),
  ('DIPET I Techniques administratives', 16, 'Licence'),
  ('DIPET II Techniques administratives', 16, 'Master'),
  ('Doctorat Techniques administratives', 3, 'Master'),
  ('DIPET I Chimie industrielle', 16, 'Licence'),
  ('DIPET II Chimie industrielle', 16, 'Master'),
  ('Diplôme d\'Etudes Supérieures Marketing', 20, 'Licence'),
  ('Diplôme d\'Etudes Supérieures Gestion du commerce international et transport', 20, 'Licence'),
  ('Diplôme d\'Etudes Supérieures Finance et comptabilité', 20, 'Licence'),
  ('Diplôme d\'Etudes Professionnelles Gestion de la vente et négociation commerciale', 25, 'Bac'),
  ('Diplôme d\'Etudes Professionnelles Gestion de l\'entrepeunariat', 25, 'Bac'),
  ('Diplôme d\'Etudes Professionnelles Gestion, analyse et évaluation des projets', 25, 'Bac'),
  ('Doctorat Économie industrielle et publique', 3, 'Master'),
  ('Doctorat Microéconomie appliquée', 3, 'Master'),
  ('Doctorat Comptabilité, audit et contrôle', 3, 'Master'),
  ('DIPET I Batîments et travaux publics', 16, 'Licence'),
  ('DIPET II Batîments et travaux publics', 16, 'Master'),
  ('Doctorat Batîments et travaux publics', 3, 'Master'),
  ('DIPET I Géomètre topographe', 16, 'Licence'),
  ('DIPET II Géomètre topographe', 16, 'Master'),
  ('Doctorat Géomètre topographe', 3, 'Master'),
  ('Doctorat Électrotechnique', 3, 'Master'),
  ('DIPET I Construction mécanique', 16, 'Licence'),
  ('DIPET II Construction mécanique', 16, 'Master'),
  ('Doctorat Construction mécanique', 3, 'Master'),
  ('Doctorat Mécanique automobile', 3, 'Master'),
  ('Doctorat Économie sociale et familiale', 3, 'Master'),
  ('DIPET I Génie informatique', 16, 'Licence');
COMMIT;

START TRANSACTION;
INSERT IGNORE INTO diplomes (nom_dip, categorie_id, niveau) VALUES
  ('DIPET II Génie informatique', 16, 'Master'),
  ('Doctorat Génie informatique', 3, 'Master'),
  ('DIPET I Sciences et techniques économiques de gestion', 16, 'Licence'),
  ('DIPET II Sciences et techniques économiques de gestion', 16, 'Master'),
  ('Doctorat Sciences et techniques économiques de gestion', 3, 'Master'),
  ('Diplôme d\'Etudes Supérieures Système d\'information et d\'aide à la gestion', 20, 'Licence'),
  ('Diplôme d\'Etudes Supérieures Audit & contrôle de gestion', 20, 'Licence'),
  ('Diplôme d\'Etudes Supérieures Gestion des ressources humaines', 20, 'Licence'),
  ('Diplôme d\'Etudes Professionnelles Gestion de la communication', 25, 'Bac'),
  ('Diplôme d\'Etudes Professionnelles Gestion de la qualité', 25, 'Bac'),
  ('Diplôme d\'Etudes Professionnelles Gestion de la politique sociale de l\'entreprise', 25, 'Bac'),
  ('MBA Gestion marketing', 8, 'Licence'),
  ('MBA Système d\'information et d\'aide à la décision', 8, 'Licence'),
  ('MBA Gestion de la production', 8, 'Licence'),
  ('Doctorat en Médecine/Pharmacie/Buccodentaire Pharmacie', 3, 'Bac'),
  ('MBA Gestion du commerce international', 8, 'Licence'),
  ('MBA Gestion financière', 8, 'Licence'),
  ('Doctorat en Médecine/Pharmacie/Buccodentaire Médecine', 3, 'Bac'),
  ('Licence Génie minier', 17, 'Bacc'),
  ('Licence Minéralurgie', 17, 'Bacc'),
  ('Diplôme d\'Ingénieur Mines - géologie', 19, 'Bac'),
  ('Diplôme d\'Ingénieur Production de pétrole et gaz', 19, 'Bac'),
  ('Diplôme d\'Ingénieur Technologie d\'extraction et de traitement des minéraux', 19, 'Bac'),
  ('Licence Géologie des ressources minérales et énergétiques', 17, 'Bacc'),
  ('Licence Métallurgie extractive', 17, 'Bacc'),
  ('Diplôme d\'Ingénieur Mines - minéralurgie - environnement', 19, 'Bac'),
  ('Diplôme d\'Ingénieur Technologies de prospection et d\'exploration minérales', 19, 'Bac'),
  ('Diplôme d\'Ingénieur Ingénierie du pétrole et du gaz', 19, 'Bac'),
  ('DUT Génie électrique', 12, 'Bacc'),
  ('DUT Génie thermique et énergétique', 12, 'Bacc'),
  ('Licence Pro Génie thermique et énergétique', 18, 'Bacc'),
  ('DUT Analyses biologiques et biochimiques', 12, 'Bacc'),
  ('Licence Pro Analyses biologiques et biochimiques', 18, 'Bacc'),
  ('DUT Industries alimentaires et biotechnologies', 12, 'Bacc'),
  ('Licence Pro Industries alimentaires et biotechnologies', 18, 'Bacc'),
  ('DUT Génie chimique et environnementale', 12, 'Bacc'),
  ('Licence Pro Génie chimique et environnementale', 18, 'Bacc'),
  ('Licence Vie familiale', 17, 'Bacc'),
  ('Master Vie familiale', 20, 'Licence'),
  ('Licence Éducation scolaire', 17, 'Bacc'),
  ('Licence Gestion et accompagnement personnel', 17, 'Bacc'),
  ('Licence Administration des affaires', 17, 'Bacc'),
  ('Licence Management et développement', 17, 'Bacc'),
  ('DIPES I Français', 16, 'Licence'),
  ('DIPES I Informatique fondamentale', 16, 'Licence'),
  ('DIPES I Sciences de la vie et de la terre', 16, 'Licence'),
  ('DIPES I Sciences de l\'éducation', 16, 'Licence'),
  ('DIPES I Géographie/éducation à la citoyenneté', 16, 'Licence'),
  ('DIPCO Conseillers d\'orientation', 32, 'Bac'),
  ('DUT Maintenance industrielle et productique', 12, 'Bacc');
COMMIT;

START TRANSACTION;
INSERT IGNORE INTO diplomes (nom_dip, categorie_id, niveau) VALUES
  ('Licence Pro Maintenance industrielle et productique', 18, 'Bacc'),
  ('DUT Génie mécanique', 12, 'Bacc'),
  ('DUT Génie de l´environnement', 12, 'Bacc'),
  ('Licence Pro Génie informatique', 18, 'Bacc'),
  ('Licence Pastorale et catéchèse', 17, 'Bacc'),
  ('Master Pastorale et catéchèse', 20, 'Licence'),
  ('Licence Vie réligieuse', 17, 'Bacc'),
  ('Master Vie réligieuse', 20, 'Licence'),
  ('Licence Éducation scolaire et humaine', 17, 'Bacc'),
  ('Licence Sciences de l\'éducation et formation des adultes', 17, 'Bacc'),
  ('Licence Finance et banque', 17, 'Bacc'),
  ('Licence Sciences informatiques', 17, 'Bacc'),
  ('DIPES I Anglais', 16, 'Licence'),
  ('DIPES I Sciences physiques', 16, 'Licence'),
  ('Diplôme de Spécialisation en Médecine/Pharmacie Chirurgie digestive', 3, 'Doctorat'),
  ('Diplôme de Spécialisation en Médecine/Pharmacie Chirurgie oncologie', 3, 'Doctorat'),
  ('Diplôme de Spécialisation en Médecine/Pharmacie Chirurgie urologie', 3, 'Doctorat'),
  ('Diplôme de Spécialisation en Médecine/Pharmacie Gynécologie obtétrique', 3, 'Doctorat'),
  ('Diplôme de Spécialisation en Médecine/Pharmacie Odontologie et chirurgie maxillo-faciale', 3, 'Doctorat'),
  ('Diplôme de Spécialisation en Médecine/Pharmacie Chirurgie spécialité ORL', 3, 'Doctorat'),
  ('Diplôme de Spécialisation en Médecine/Pharmacie Santé publique spécialité psychiatrie', 3, 'Doctorat'),
  ('Diplôme de Spécialisation en Médecine/Pharmacie Biophysique / cancérologie', 3, 'Doctorat'),
  ('Diplôme de Spécialisation en Médecine/Pharmacie Dermatologie', 3, 'Doctorat'),
  ('Diplôme de Spécialisation en Médecine/Pharmacie Gastro entérologie', 3, 'Doctorat'),
  ('Diplôme de Spécialisation en Médecine/Pharmacie Neurologie', 3, 'Doctorat'),
  ('Diplôme de Spécialisation en Médecine/Pharmacie Pneumo physiologie', 3, 'Doctorat'),
  ('Diplôme de Spécialisation en Médecine/Pharmacie Ana pathologie / histologie', 3, 'Doctorat'),
  ('Diplôme de Spécialisation en Médecine/Pharmacie Sciences pharmaceutiques spécialité biologie végét', 3, 'Doctorat'),
  ('Diplôme de Spécialisation en Médecine/Pharmacie Sciences pharmaceutiques spécialité chimie inorgan', 3, 'Doctorat'),
  ('Diplôme de Spécialisation en Médecine/Pharmacie Sciences pharmaceutiques spécialité pharmacie', 3, 'Doctorat'),
  ('Licence Pro Cadre des collectivités locales et décentralisées', 18, 'Bacc'),
  ('Licence Pro Transport et procédures de dédouanement', 18, 'Bacc'),
  ('Licence Pro Fiscalité appliquée', 18, 'Bacc'),
  ('Diplôme de Spécialisation en Médecine/Pharmacie Chirurgie générale', 3, 'Doctorat'),
  ('Diplôme de Spécialisation en Médecine/Pharmacie Chirurgie orthopédie', 3, 'Doctorat'),
  ('Diplôme de Spécialisation en Médecine/Pharmacie Chirurgie viscérale', 3, 'Doctorat'),
  ('Diplôme de Spécialisation en Médecine/Pharmacie Neurochirurgie', 3, 'Doctorat'),
  ('Diplôme de Spécialisation en Médecine/Pharmacie Chirurgie spécialité ophtamologie / strabologie', 3, 'Doctorat'),
  ('Diplôme de Spécialisation en Médecine/Pharmacie Santé publique spécialité épidémiologie', 3, 'Doctorat'),
  ('Diplôme de Spécialisation en Médecine/Pharmacie Cardiologie', 3, 'Doctorat'),
  ('Diplôme de Spécialisation en Médecine/Pharmacie Endocrinologie', 3, 'Doctorat'),
  ('Diplôme de Spécialisation en Médecine/Pharmacie Néphrologie', 3, 'Doctorat'),
  ('Diplôme de Spécialisation en Médecine/Pharmacie Pédiatrie', 3, 'Doctorat'),
  ('Diplôme de Spécialisation en Médecine/Pharmacie Radiologie et imagerie médicale', 3, 'Doctorat'),
  ('Diplôme de Spécialisation en Médecine/Pharmacie Sciences pharmaceutiques spécialité biologie anima', 3, 'Doctorat'),
  ('Diplôme de Spécialisation en Médecine/Pharmacie Sciences pharmaceutiques spécialité chimie', 3, 'Doctorat'),
  ('Diplôme de Spécialisation en Médecine/Pharmacie Sciences pharmaceutiques spécialité chimie organiq', 3, 'Doctorat'),
  ('Diplôme de Spécialisation en Médecine/Pharmacie Sciences pharmaceutiques spécialité pharmacologie', 3, 'Doctorat'),
  ('Licence Pro Cadres judiciares et cadres administratifs', 18, 'Bacc'),
  ('Licence Pro Banques et finances', 18, 'Bacc');
COMMIT;

START TRANSACTION;
INSERT IGNORE INTO diplomes (nom_dip, categorie_id, niveau) VALUES
  ('Diplôme de Spécialisation en Médecine/Pharmacie Chirurgie spécialité anesthésie - réanimation', 3, 'Doctorat'),
  ('Diplôme de Spécialisation en Médecine/Pharmacie Chirurgie spécialité anatomie', 3, 'Doctorat'),
  ('Licence Arts de la scène et art visuels', 17, 'Bacc'),
  ('Licence Linguistique théorique', 17, 'Bacc'),
  ('Master Linguistique théorique', 20, 'Licence'),
  ('Doctorat Linguistique théorique', 3, 'Master'),
  ('Licence Français', 17, 'Bacc'),
  ('Licence Botanique', 17, 'Bacc'),
  ('Master Botanique', 20, 'Licence'),
  ('Doctorat Botanique', 3, 'Master'),
  ('Licence Géologie', 17, 'Bacc'),
  ('Master Géologie', 20, 'Licence'),
  ('Doctorat Géologie', 3, 'Master'),
  ('Licence Microbiologie', 17, 'Bacc'),
  ('Master Microbiologie', 20, 'Licence'),
  ('Doctorat Microbiologie', 3, 'Master'),
  ('Master Mathématiques', 20, 'Licence'),
  ('Doctorat Mathématiques', 3, 'Master'),
  ('Licence Zoologie', 17, 'Bacc'),
  ('Master Zoologie', 20, 'Licence'),
  ('Doctorat Zoologie', 3, 'Master'),
  ('Licence Études des cursus et de l\'enseignement', 17, 'Bacc'),
  ('Master Études des cursus et de l\'enseignement', 20, 'Licence'),
  ('Doctorat Études des cursus et de l\'enseignement', 3, 'Master'),
  ('Licence Administration de l\'éducation et éducation spécial', 17, 'Bacc'),
  ('Master Administration de l\'éducation et éducation spécial', 20, 'Licence'),
  ('Doctorat Administration de l\'éducation et éducation spécial', 3, 'Master'),
  ('Licence Journalisme et communication de masse', 17, 'Bacc'),
  ('Licence Femme et études sur le genre', 17, 'Bacc'),
  ('Master Femme et études sur le genre', 20, 'Licence'),
  ('Doctorat Femme et études sur le genre', 3, 'Master'),
  ('Licence Management de la santé des plantes', 17, 'Bacc'),
  ('Licence Foresterie et faune', 17, 'Bacc'),
  ('Licence Technologie et sciences des aliments', 17, 'Bacc'),
  ('Licence Sciences agronomiques et moléculaires appliquées', 17, 'Bacc'),
  ('Licence Anglais-français', 17, 'Bacc'),
  ('Licence Littérature africaine', 17, 'Bacc'),
  ('Master Littérature africaine', 20, 'Licence'),
  ('Doctorat Littérature africaine', 3, 'Master'),
  ('Licence Sciences de l\'environnement', 17, 'Bacc'),
  ('Licence Psychologie de l\'éducation', 17, 'Bacc'),
  ('Master Psychologie de l\'éducation', 20, 'Licence'),
  ('Doctorat Psychologie de l\'éducation', 3, 'Master'),
  ('Licence Banques finances et comptablité', 17, 'Bacc'),
  ('Licence Droit', 17, 'Bacc'),
  ('Master Droit', 20, 'Licence'),
  ('Doctorat Droit', 3, 'Master'),
  ('Doctorat Management', 3, 'Master'),
  ('Licence Économie agricole et agri business', 17, 'Bacc'),
  ('Licence Médecine vétérinaire', 17, 'Bacc');
COMMIT;

START TRANSACTION;
INSERT IGNORE INTO diplomes (nom_dip, categorie_id, niveau) VALUES
  ('Licence Extension agricole et développement rural', 17, 'Bacc'),
  ('Licence Pro Comptabilité et finances', 18, 'Bacc'),
  ('Licence Pro Informatique et génie logiciel', 18, 'Bacc'),
  ('Licence Pro Gestion et administration de l\'eglise', 18, 'Bacc'),
  ('Licence Pro Gestion des entreprises et des administrations', 18, 'Bacc'),
  ('Licence Pro Informatique et gestion', 18, 'Bacc'),
  ('Licence Pro Théologie', 18, 'Bacc'),
  ('Licence Pro Sciences juridiques et politiques', 18, 'Bacc'),
  ('Licence Linguistique générale appliquée', 17, 'Bacc'),
  ('Master Linguistique générale appliquée', 20, 'Licence'),
  ('Doctorat Linguistique générale appliquée', 3, 'Master'),
  ('Licence Art  du spectacle et cinématographique', 17, 'Bacc'),
  ('Master Art  du spectacle et cinématographique', 20, 'Licence'),
  ('Doctorat Art  du spectacle et cinématographique', 3, 'Master'),
  ('Licence Archéologies et gestion du patrimoine', 17, 'Bacc'),
  ('Master Archéologies et gestion du patrimoine', 20, 'Licence'),
  ('Doctorat Archéologies et gestion du patrimoine', 3, 'Master'),
  ('Licence Management des entreprises touristiques', 17, 'Bacc'),
  ('Master Management des entreprises touristiques', 20, 'Licence'),
  ('Doctorat Management des entreprises touristiques', 3, 'Master'),
  ('Licence Lettres bilingues (francophone)', 17, 'Bacc'),
  ('Master Lettres bilingues (francophone)', 20, 'Licence'),
  ('Doctorat Lettres bilingues (francophone)', 3, 'Master'),
  ('Licence Littérature et civilisation africaine', 17, 'Bacc'),
  ('Master Littérature et civilisation africaine', 20, 'Licence'),
  ('Doctorat Littérature et civilisation africaine', 3, 'Master'),
  ('Licence Art plastique et histoire de l´art', 17, 'Bacc'),
  ('Master Art plastique et histoire de l´art', 20, 'Licence'),
  ('Doctorat Art plastique et histoire de l´art', 3, 'Master'),
  ('Licence Guide touristique', 17, 'Bacc'),
  ('Master Guide touristique', 20, 'Licence'),
  ('Doctorat Guide touristique', 3, 'Master'),
  ('Licence Biologie animale', 17, 'Bacc'),
  ('Master Biologie animale', 20, 'Licence'),
  ('Doctorat Biologie animale', 3, 'Master'),
  ('Licence Biologie et physiologie végétale', 17, 'Bacc'),
  ('Master Biologie et physiologie végétale', 20, 'Licence'),
  ('Doctorat Biologie et physiologie végétale', 3, 'Master'),
  ('Doctorat Informatique', 3, 'Master'),
  ('Licence Modélisation des ecoulements', 17, 'Bacc'),
  ('Master Modélisation des ecoulements', 20, 'Licence'),
  ('Licence Biochimie médicale', 17, 'Bacc'),
  ('Master Biochimie médicale', 20, 'Licence'),
  ('Licence Hématologie et transfusion sanguine', 17, 'Bacc'),
  ('Master Hématologie et transfusion sanguine', 20, 'Licence'),
  ('Licence Radiologie et imagerie médicales', 17, 'Bacc'),
  ('Master Radiologie et imagerie médicales', 20, 'Licence'),
  ('Licence Distribution vente', 17, 'Bacc'),
  ('Licence Gestion du produit', 17, 'Bacc'),
  ('Licence Économie et finances internationales', 17, 'Bacc');
COMMIT;

START TRANSACTION;
INSERT IGNORE INTO diplomes (nom_dip, categorie_id, niveau) VALUES
  ('Master Économie et finances internationales', 20, 'Licence'),
  ('Licence Droit privé fondamental', 17, 'Bacc'),
  ('Licence Génétique et biostatistique', 17, 'Bacc'),
  ('Master Génétique et biostatistique', 20, 'Licence'),
  ('Licence Pathologie médicale et chirurgicale', 17, 'Bacc'),
  ('Master Pathologie médicale et chirurgicale', 20, 'Licence'),
  ('Licence Physiologie et biochimie', 17, 'Bacc'),
  ('Master Physiologie et biochimie', 20, 'Licence'),
  ('Licence Microbiologie et pathologies infectieuses', 17, 'Bacc'),
  ('Master Microbiologie et pathologies infectieuses', 20, 'Licence'),
  ('Licence Pharmacie, pharmacologie et toxicologie', 17, 'Bacc'),
  ('Master Pharmacie, pharmacologie et toxicologie', 20, 'Licence'),
  ('Licence Enseignements fondamentaux en éducation', 17, 'Bacc'),
  ('Master Enseignements fondamentaux en éducation', 20, 'Licence'),
  ('Doctorat Enseignements fondamentaux en éducation', 3, 'Master'),
  ('Licence Mesure et évaluation', 17, 'Bacc'),
  ('Master Mesure et évaluation', 20, 'Licence'),
  ('Doctorat Mesure et évaluation', 3, 'Master'),
  ('Licence Psychologie et sciences de l\'orientation', 17, 'Bacc'),
  ('Master Psychologie et sciences de l\'orientation', 20, 'Licence'),
  ('Doctorat Psychologie et sciences de l\'orientation', 3, 'Master'),
  ('Licence Microbiologie, parasitologie et immunologie médicales', 17, 'Bacc'),
  ('Master Microbiologie, parasitologie et immunologie médicales', 20, 'Licence'),
  ('Licence Sciences médico-sanitaires', 17, 'Bacc'),
  ('Master Sciences médico-sanitaires', 20, 'Licence'),
  ('Licence Communication commerciale', 17, 'Bacc'),
  ('Licence Management général', 17, 'Bacc'),
  ('Licence Métiers bancaires', 17, 'Bacc'),
  ('Licence Droit fondamental', 17, 'Bacc'),
  ('Master Droit fondamental', 20, 'Licence'),
  ('Licence Anatomie, histologie et embryologie', 17, 'Bacc'),
  ('Master Anatomie, histologie et embryologie', 20, 'Licence'),
  ('Licence Parasitologie et maladies parasitaires', 17, 'Bacc'),
  ('Master Parasitologie et maladies parasitaires', 20, 'Licence'),
  ('Licence Production animale', 17, 'Bacc'),
  ('Master Production animale', 20, 'Licence'),
  ('Licence Physiologie et biotechnologie de la reproduction', 17, 'Bacc'),
  ('Master Physiologie et biotechnologie de la reproduction', 20, 'Licence'),
  ('Licence Hygiène et industries des denrées alimentaire d´origine animale', 17, 'Bacc'),
  ('Master Hygiène et industries des denrées alimentaire d´origine animale', 20, 'Licence'),
  ('Licence Administration de l\'éducation', 17, 'Bacc'),
  ('Master Administration de l\'éducation', 20, 'Licence'),
  ('Doctorat Administration de l\'éducation', 3, 'Master'),
  ('Licence Éducation physique, santé et loisirs', 17, 'Bacc'),
  ('Master Éducation physique, santé et loisirs', 20, 'Licence'),
  ('Doctorat Éducation physique, santé et loisirs', 3, 'Master'),
  ('Licence Génie informatique et télécommunication', 17, 'Bacc'),
  ('Licence Télécommunications', 17, 'Bacc'),
  ('Master Télécommunications', 20, 'Licence'),
  ('Licence Traduction et études interculturelles', 17, 'Bacc');
COMMIT;

START TRANSACTION;
INSERT IGNORE INTO diplomes (nom_dip, categorie_id, niveau) VALUES
  ('Licence Biochimie et laboratoire de technologie chimique', 17, 'Bacc'),
  ('Licence Horticulture', 17, 'Bacc'),
  ('Licence Science matériel et technologie', 17, 'Bacc'),
  ('Licence Chimiepharmaceutique', 17, 'Bacc'),
  ('Licence Parasitologie', 17, 'Bacc'),
  ('Licence Physique appliqué', 17, 'Bacc'),
  ('Licence Conseils d\'orientation', 17, 'Bacc'),
  ('Master Conseils d\'orientation', 20, 'Licence'),
  ('Doctorat Conseils d\'orientation', 3, 'Master'),
  ('Licence Sciences des laboratoires médicaux', 17, 'Bacc'),
  ('Master Interprétariat', 20, 'Licence'),
  ('Master Langue anglaise', 20, 'Licence'),
  ('Doctorat Langue anglaise', 3, 'Master'),
  ('Master Protection des cultures', 20, 'Licence'),
  ('Master Journalisme', 20, 'Licence'),
  ('Master Littérature comparée', 20, 'Licence'),
  ('Doctorat Littérature comparée', 3, 'Master'),
  ('Master Pathologie chimique', 20, 'Licence'),
  ('Licence Maintenance des réseaux et systèmes informatiques', 17, 'Bacc'),
  ('Master Maintenance des réseaux et systèmes informatiques', 20, 'Licence'),
  ('Licence Technologie électrique', 17, 'Bacc'),
  ('Master Technologie électrique', 20, 'Licence'),
  ('Licence Biologie moléculaire', 17, 'Bacc'),
  ('Licence Processus de technologie chimique', 17, 'Bacc'),
  ('Licence Chimie et laboratoire de technologique chimique', 17, 'Bacc'),
  ('Licence Technologie du pétrole', 17, 'Bacc'),
  ('Licence Diagnostique des maladies infectieuses', 17, 'Bacc'),
  ('Licence Physique - option électricité', 17, 'Bacc'),
  ('Licence Affaires des administrations', 17, 'Bacc'),
  ('Licence Sciences alimentaires et nutrition', 17, 'Bacc'),
  ('Licence Génie logiciel', 17, 'Bacc'),
  ('Master Génie logiciel', 20, 'Licence'),
  ('Master Traduction', 20, 'Licence'),
  ('Master Linguistique appliquée', 20, 'Licence'),
  ('Doctorat Linguistique appliquée', 3, 'Master'),
  ('Master Littérature américaine', 20, 'Licence'),
  ('Doctorat Littérature américaine', 3, 'Master'),
  ('Master Géologie appliquée', 20, 'Licence'),
  ('Doctorat Géologie appliquée', 3, 'Master'),
  ('Master Éducation infirmière', 20, 'Licence'),
  ('Licence Pro Génie des réseaux et télécommunications (GRT)', 18, 'Bacc'),
  ('Licence Pro Gestion comptable et finance (GCF)', 18, 'Bacc'),
  ('Licence Pro Génie logiciel (GL)', 18, 'Bacc'),
  ('Licence Géologie (sciences de la terre)', 17, 'Bacc'),
  ('Master Géologie (sciences de la terre)', 20, 'Licence'),
  ('Doctorat Géologie (sciences de la terre)', 3, 'Master'),
  ('Licence Radiologie et  imagerie  médicales', 17, 'Bacc'),
  ('Master Radiologie et  imagerie  médicales', 20, 'Licence'),
  ('Licence Études médicales', 17, 'Bacc'),
  ('Master Études médicales', 20, 'Licence');
COMMIT;

START TRANSACTION;
INSERT IGNORE INTO diplomes (nom_dip, categorie_id, niveau) VALUES
  ('Doctorat en Médecine/Pharmacie/Buccodentaire Études médicales', 3, 'Bac'),
  ('Licence Études de médecine bucco-dentaires', 17, 'Bacc'),
  ('Master Études de médecine bucco-dentaires', 20, 'Licence'),
  ('Doctorat en Médecine/Pharmacie/Buccodentaire Études de médecine bucco-dentaires', 3, 'Bac'),
  ('Licence Finance internationale', 17, 'Bacc'),
  ('Master Finance internationale', 20, 'Licence'),
  ('Licence Maintien de la paix', 17, 'Bacc'),
  ('Master Maintien de la paix', 20, 'Licence'),
  ('Licence Histoire de l\'église et du christianisme', 17, 'Bacc'),
  ('Master Histoire de l\'église et du christianisme', 20, 'Licence'),
  ('Doctorat Histoire de l\'église et du christianisme', 3, 'Master'),
  ('Licence Études pharmaceutiques', 17, 'Bacc'),
  ('Master Études pharmaceutiques', 20, 'Licence'),
  ('Doctorat en Médecine/Pharmacie/Buccodentaire Études pharmaceutiques', 3, 'Bac'),
  ('Licence Diplomatie', 17, 'Bacc'),
  ('Licence Communication internationale', 17, 'Bacc'),
  ('Licence Développement durable, rural et communautaire', 17, 'Bacc'),
  ('Master Développement durable, rural et communautaire', 20, 'Licence'),
  ('Licence Prévention et résolution des conflits', 17, 'Bacc'),
  ('Master Prévention et résolution des conflits', 20, 'Licence'),
  ('Licence Dogmatique et éthique', 17, 'Bacc'),
  ('Master Dogmatique et éthique', 20, 'Licence'),
  ('Doctorat Dogmatique et éthique', 3, 'Master'),
  ('Licence Théologie pratique de la cure de l\'âme', 17, 'Bacc'),
  ('Master Théologie pratique de la cure de l\'âme', 20, 'Licence'),
  ('Doctorat Théologie pratique de la cure de l\'âme', 3, 'Master'),
  ('Licence Histoire des religions', 17, 'Bacc'),
  ('Master Histoire des religions', 20, 'Licence'),
  ('Doctorat Histoire des religions', 3, 'Master'),
  ('Licence Missiologie', 17, 'Bacc'),
  ('Master Missiologie', 20, 'Licence'),
  ('Doctorat Missiologie', 3, 'Master'),
  ('Doctorat Lettres d\'expression française', 3, 'Master'),
  ('Licence Arts', 17, 'Bacc'),
  ('Master Arts', 20, 'Licence'),
  ('Doctorat Arts', 3, 'Master'),
  ('Licence Langue africaine', 17, 'Bacc'),
  ('Master Langue africaine', 20, 'Licence'),
  ('Licence Electronique, electrotechnique et automatique', 17, 'Bacc'),
  ('Master Electronique, electrotechnique et automatique', 20, 'Licence'),
  ('Licence Mécanique et matériaux', 17, 'Bacc'),
  ('Master Mécanique et matériaux', 20, 'Licence'),
  ('Licence Biologie des organismes', 17, 'Bacc'),
  ('Master Biologie des organismes', 20, 'Licence'),
  ('Licence Biologie et physiologie animales', 17, 'Bacc'),
  ('Master Biologie et physiologie animales', 20, 'Licence'),
  ('Licence Etude de la géologie du territoire camerounais et de l´afrique', 17, 'Bacc'),
  ('Master Etude de la géologie du territoire camerounais et de l´afrique', 20, 'Licence'),
  ('Licence Exploration des ressources minières', 17, 'Bacc'),
  ('Master Exploration des ressources minières', 20, 'Licence');
COMMIT;

START TRANSACTION;
INSERT IGNORE INTO diplomes (nom_dip, categorie_id, niveau) VALUES
  ('Licence Prévention des risques naturels', 17, 'Bacc'),
  ('Master Prévention des risques naturels', 20, 'Licence'),
  ('Licence Métallogénie et gitologie', 17, 'Bacc'),
  ('Master Métallogénie et gitologie', 20, 'Licence'),
  ('Licence Chimie appliquée', 17, 'Bacc'),
  ('Master Chimie appliquée', 20, 'Licence'),
  ('Licence Chimie organique', 17, 'Bacc'),
  ('Master Chimie organique', 20, 'Licence'),
  ('Licence Mathématiques et informatique', 17, 'Bacc'),
  ('Master Mathématiques et informatique', 20, 'Licence'),
  ('Licence Calcul  scientifique', 17, 'Bacc'),
  ('Master Calcul  scientifique', 20, 'Licence'),
  ('Licence Epidémiologie mathématique', 17, 'Bacc'),
  ('Master Epidémiologie mathématique', 20, 'Licence'),
  ('Licence Linguistique', 17, 'Bacc'),
  ('Master Linguistique', 20, 'Licence'),
  ('Licence Atomes, molécules et interactions', 17, 'Bacc'),
  ('Master Atomes, molécules et interactions', 20, 'Licence'),
  ('Licence Géochimie et cartographie', 17, 'Bacc'),
  ('Master Géochimie et cartographie', 20, 'Licence'),
  ('Licence Cartographie, géochimie et métallogénie', 17, 'Bacc'),
  ('Master Cartographie, géochimie et métallogénie', 20, 'Licence'),
  ('Licence Chimie inorganique', 17, 'Bacc'),
  ('Master Chimie inorganique', 20, 'Licence'),
  ('Licence Sciences et techniques de l´informatique', 17, 'Bacc'),
  ('Master Sciences et techniques de l´informatique', 20, 'Licence'),
  ('Doctorat Parasitologie cellulaire et moléculaire', 3, 'Master'),
  ('Doctorat Pêche', 3, 'Master'),
  ('Doctorat Médecine', 3, 'Master'),
  ('Doctorat Pharmacie', 3, 'Master'),
  ('Doctorat Production animale', 3, 'Master'),
  ('Doctorat Communication de masse', 3, 'Master'),
  ('Doctorat Chirurgie dentaire', 3, 'Master'),
  ('Licence Didactique des disciplines', 17, 'Bacc'),
  ('Master Didactique des disciplines', 20, 'Licence'),
  ('Doctorat Didactique des disciplines', 3, 'Master'),
  ('Licence Management de l´éducation', 17, 'Bacc'),
  ('Master Management de l´éducation', 20, 'Licence'),
  ('Doctorat Management de l´éducation', 3, 'Master'),
  ('Licence Langues, littérature et civilisations ibériques, ibéro-américaines et italiennes (espagnol)', 17, 'Bacc'),
  ('Master Langues, littérature et civilisations ibériques, ibéro-américaines et italiennes (espagnol)', 20, 'Licence'),
  ('Doctorat Langues, littérature et civilisations ibériques, ibéro-américaines et italiennes (espagnol)', 3, 'Master'),
  ('Licence Sciences du langage', 17, 'Bacc'),
  ('Master Sciences du langage', 20, 'Licence'),
  ('Doctorat Sciences du langage', 3, 'Master'),
  ('Licence Information documentaire', 17, 'Bacc'),
  ('Master Pro Information documentaire', 22, 'Licence'),
  ('Master Banque - monnaie', 20, 'Licence'),
  ('Master Diplomatie classique', 20, 'Licence'),
  ('Master Foresterie', 20, 'Licence');
COMMIT;

START TRANSACTION;
INSERT IGNORE INTO diplomes (nom_dip, categorie_id, niveau) VALUES
  ('Master Génie civil', 20, 'Licence'),
  ('Licence Curriculum et évaluation', 17, 'Bacc'),
  ('Master Curriculum et évaluation', 20, 'Licence'),
  ('Doctorat Curriculum et évaluation', 3, 'Master'),
  ('Licence Intervention, orientation et éducation extrascolaire', 17, 'Bacc'),
  ('Master Intervention, orientation et éducation extrascolaire', 20, 'Licence'),
  ('Doctorat Intervention, orientation et éducation extrascolaire', 3, 'Master'),
  ('Licence Lettres bilingues (anglophone)', 17, 'Bacc'),
  ('Master Lettres bilingues (anglophone)', 20, 'Licence'),
  ('Doctorat Lettres bilingues (anglophone)', 3, 'Master'),
  ('Licence Langues, littérature et civilisations germaniques (allemand)', 17, 'Bacc'),
  ('Master Langues, littérature et civilisations germaniques (allemand)', 20, 'Licence'),
  ('Doctorat Langues, littérature et civilisations germaniques (allemand)', 3, 'Master'),
  ('Master Pro Journalisme', 22, 'Licence'),
  ('Licence Publicité', 17, 'Bacc'),
  ('Master Pro Publicité', 22, 'Licence'),
  ('Licence Édition et arts graphiques', 17, 'Bacc'),
  ('Master Pro Édition et arts graphiques', 22, 'Licence'),
  ('Licence Archivistique et records management', 17, 'Bacc'),
  ('Master Contentieux international', 20, 'Licence'),
  ('Master Communication et action publique internationales', 20, 'Licence'),
  ('Master Agronomie', 20, 'Licence'),
  ('Master Génie mécanique', 20, 'Licence'),
  ('Master Génie chimique', 20, 'Licence'),
  ('Master Sciences alimentaires et nutrition', 20, 'Licence'),
  ('Master Energétique', 20, 'Licence'),
  ('Master Comptabilité -finance', 20, 'Licence'),
  ('Master Sciences et techniques de gestion', 20, 'Licence'),
  ('Master Gestion logistique', 20, 'Licence'),
  ('Master Audit social', 20, 'Licence'),
  ('Master Techniques bancaires et financières', 20, 'Licence'),
  ('Diplôme d\'Ingénieur Maintenance industrielle et productique', 19, 'Bac'),
  ('Diplôme d\'Ingénieur Bioprocédés et chimie industrielle', 19, 'Bac'),
  ('Diplôme d\'Ingénieur Génie minéral', 19, 'Bac'),
  ('Doctorat Comptabilité et contrôle', 3, 'Master'),
  ('Doctorat Génie des procédés', 3, 'Master'),
  ('Doctorat Nutrition', 3, 'Master'),
  ('Master Pro Sécurité industrielle et management de l´environnement', 22, 'Licence'),
  ('Master Génie alimentaire et bioprocédés', 20, 'Licence'),
  ('Master Sciences et technologies post-récoltes', 20, 'Licence'),
  ('Master Chimie industrielle et environnement', 20, 'Licence'),
  ('Master Mécanique et productique', 20, 'Licence'),
  ('Master Marketing-commerce-vente', 20, 'Licence'),
  ('Master Administration générale des entreprises', 20, 'Licence'),
  ('Diplôme d\'Ingénieur Industries agricoles et alimentaires', 19, 'Bac'),
  ('Diplôme d\'Ingénieur Chimie industrielle et  génie de l´environnement', 19, 'Bac'),
  ('Diplôme d\'Ingénieur Génie analytique et productique', 19, 'Bac'),
  ('Diplôme d\'Ingénieur Génie des matériaux', 19, 'Bac'),
  ('Doctorat Sciences des aliments', 3, 'Master'),
  ('Master Pro Nutrition appliquée', 22, 'Licence');
COMMIT;

START TRANSACTION;
INSERT IGNORE INTO diplomes (nom_dip, categorie_id, niveau) VALUES
  ('Master Pro Comptabilité et finances', 22, 'Licence'),
  ('Master Pro Droit communautaire et de l\'intégration régionale', 22, 'Licence'),
  ('Master Pro Juriste conseil d\'entreprise', 22, 'Licence'),
  ('Master Pro Administration et gouvernance urbaine et locale', 22, 'Licence'),
  ('Master Pro Contentieux public et privé', 22, 'Licence'),
  ('Master Pro Fiscalité (administration fiscale + fiscalité appliquée)', 22, 'Licence'),
  ('Master Pro Transport internationaux subsahariens et logistique', 22, 'Licence'),
  ('Master Coopération internationale, action humanitaire et développement durable', 20, 'Licence'),
  ('Master Diversité culturelle, paix et coopération internationale', 20, 'Licence'),
  ('Master Chirurgie et spécialités', 20, 'Licence'),
  ('Master Gynéco-obstétrique', 20, 'Licence'),
  ('Master Ophtalmologie et en orl', 20, 'Licence'),
  ('Master Bactériologie - virologie médicale', 20, 'Licence'),
  ('Master Francophonie et mondialisation', 20, 'Licence'),
  ('Master Intégration régionale et management des institutions communautaires', 20, 'Licence'),
  ('Master Médecine interne et spécialités médicales', 20, 'Licence'),
  ('Master Pédiatrie', 20, 'Licence'),
  ('Master Anesthésie-réanimation', 20, 'Licence'),
  ('Master Parasitologie - mycologie médicale', 20, 'Licence'),
  ('Licence Pro Laboratoire de technologie médicale', 18, 'Bacc'),
  ('BTS Chimie et pétrochimie et informatique', 5, 'Bac'),
  ('Licence Pro Chimie et pétrochimie et informatique', 18, 'Bacc'),
  ('BTS Génie communication et réseaux', 5, 'Bac'),
  ('Licence Pro Génie communication et réseaux', 18, 'Bacc'),
  ('BTS Mécanique et électricité', 5, 'Bac'),
  ('Licence Pro Mécanique et électricité', 18, 'Bacc'),
  ('Master Pro Mécanique et électricité', 22, 'Licence'),
  ('BTS Assurances', 5, 'Bac'),
  ('Licence Pro Assurances', 18, 'Bacc'),
  ('BTS Commerce et gestion', 5, 'Bac'),
  ('Licence Pro Commerce et gestion', 18, 'Bacc'),
  ('Licence Pro Comptabilité et gestion des entreprises', 18, 'Bacc'),
  ('BTS Planification urbaine et rurale et gestion des risques environnementaux', 5, 'Bac'),
  ('Licence Pro Planification urbaine et rurale et gestion des risques environnementaux', 18, 'Bacc'),
  ('BTS Secrétariat et bureautique', 5, 'Bac'),
  ('Licence Pro Secrétariat et bureautique', 18, 'Bacc'),
  ('BTS Topographie', 5, 'Bac'),
  ('Licence Pro Topographie', 18, 'Bacc'),
  ('Licence Pro Action commerciale', 18, 'Bacc'),
  ('Licence Pro Agronomie - production végétale', 18, 'Bacc'),
  ('Master Pro Agronomie - production végétale', 22, 'Licence'),
  ('Licence Pro Ingénieur en économie rurale', 18, 'Bacc'),
  ('Master Pro Ingénieur en économie rurale', 22, 'Licence'),
  ('Master Pro Entrepreneuriat et agri business en production végétale', 22, 'Licence'),
  ('BTS Études maritimes et portuaire', 5, 'Bac'),
  ('Licence Pro Études maritimes et portuaire', 18, 'Bacc'),
  ('Master Pro Études maritimes et portuaire', 22, 'Licence'),
  ('BTS Génie civil informatique', 5, 'Bac'),
  ('Licence Pro Génie civil informatique', 18, 'Bacc'),
  ('Master Pro Génie civil informatique', 22, 'Licence');
COMMIT;

START TRANSACTION;
INSERT IGNORE INTO diplomes (nom_dip, categorie_id, niveau) VALUES
  ('BTS Banque', 5, 'Bac'),
  ('Licence Pro Banque', 18, 'Bacc'),
  ('BTS Géoinformatique', 5, 'Bac'),
  ('Licence Pro Géoinformatique', 18, 'Bacc'),
  ('BTS Planification urbaine', 5, 'Bac'),
  ('Licence Pro Planification urbaine', 18, 'Bacc'),
  ('BTS Politique et administration foncière', 5, 'Bac'),
  ('Licence Pro Politique et administration foncière', 18, 'Bacc'),
  ('BTS Système d\'information géographique et d\'élection à distance', 5, 'Bac'),
  ('Licence Pro Système d\'information géographique et d\'élection à distance', 18, 'Bacc'),
  ('Licence Pro Agronomie - production animal', 18, 'Bacc'),
  ('Master Pro Agronomie - production animal', 22, 'Licence'),
  ('Licence Pro Agronomie - transformation de produits', 18, 'Bacc'),
  ('Master Pro Agronomie - transformation de produits', 22, 'Licence'),
  ('Master Pro Entrepreneuriat et agri business en production animale', 22, 'Licence'),
  ('Licence Pro Laboratoire technologie chimique', 18, 'Bacc'),
  ('Master Pro Biotechnologie', 22, 'Licence'),
  ('Master Pro Ressources naturelles et management environnemental.', 22, 'Licence'),
  ('Master Pro Pêche et production animale', 22, 'Licence'),
  ('Licence Pro Zoologie et laboratoire de technologie chimique', 18, 'Bacc'),
  ('Master Pro Science du diagnostique moléculaire', 22, 'Licence'),
  ('Master Pro Épidémiologie et contrôle des maladies infectieuses', 22, 'Licence'),
  ('Master Pro Enseignement du français comme langue etrangère', 22, 'Licence'),
  ('Licence Art plastique et histoire de l\'art', 17, 'Bacc'),
  ('Master Art plastique et histoire de l\'art', 20, 'Licence'),
  ('Licence Musicologie, gestion et conservation du patrimoine', 17, 'Bacc'),
  ('Master Musicologie, gestion et conservation du patrimoine', 20, 'Licence'),
  ('Licence Industrie cinématographiques et audiovisuelles', 17, 'Bacc'),
  ('Master Industrie cinématographiques et audiovisuelles', 20, 'Licence'),
  ('Licence Art, culture et religion', 17, 'Bacc'),
  ('Master Art, culture et religion', 20, 'Licence'),
  ('Licence Cinéma et audiovisuel', 17, 'Bacc'),
  ('Master Cinéma et audiovisuel', 20, 'Licence'),
  ('Licence Architecture et urbanisme', 17, 'Bacc'),
  ('Master Architecture et urbanisme', 20, 'Licence'),
  ('Licence Études théâtrales', 17, 'Bacc'),
  ('Master Études théâtrales', 20, 'Licence'),
  ('Licence Patrimoine, musélogie et tourisme', 17, 'Bacc'),
  ('Master Patrimoine, musélogie et tourisme', 20, 'Licence'),
  ('Master Pro Administration des collectivités publiques', 22, 'Licence'),
  ('Master Pro Management des établissementss scolaires', 22, 'Licence'),
  ('Master Pro Management des ong', 22, 'Licence'),
  ('Master Pro Norme et qualité des produits alimentaires', 22, 'Licence'),
  ('Master Pro Administration publique', 22, 'Licence'),
  ('Master Pro Management des établissementss scolaires hospitaliers', 22, 'Licence'),
  ('Master Pro Norme appliquée à l\'exploitation forestière', 22, 'Licence'),
  ('Master Pro Norme et qualité des produits phytosanitaires', 22, 'Licence'),
  ('Master Immunologie médicale', 20, 'Licence'),
  ('Master Pharmacognosie médicale', 20, 'Licence'),
  ('Diplôme d\'Ingénieur Sécurités des réseaux', 19, 'Bac');
COMMIT;

START TRANSACTION;
INSERT IGNORE INTO diplomes (nom_dip, categorie_id, niveau) VALUES
  ('Diplôme d\'Ingénieur Génie civil', 19, 'Bac'),
  ('Diplôme d\'Ingénieur Génie mécanique', 19, 'Bac'),
  ('Diplôme d\'Ingénieur Art numérique', 19, 'Bac'),
  ('Doctorat Démographie formelle', 3, 'Master'),
  ('Doctorat Population - economie - société', 3, 'Master'),
  ('DIPES I Science de l´education', 16, 'Licence'),
  ('DIPES II Science de l´education', 16, 'Master'),
  ('DIPES II Anglais', 16, 'Master'),
  ('DIPES I Lettres classiques', 16, 'Licence'),
  ('DIPES II Lettres classiques', 16, 'Master'),
  ('DEUG Mathématiques', 12, 'Bac'),
  ('Master Maladies infectieuses', 20, 'Licence'),
  ('Master Marketing international', 20, 'Licence'),
  ('Diplôme d\'Ingénieur Services et radio mobile', 19, 'Bac'),
  ('Diplôme d\'Ingénieur Génie électrique', 19, 'Bac'),
  ('Diplôme d\'Ingénieur Génie informatique', 19, 'Bac'),
  ('Diplôme d\'Ingénieur Génie industriel', 19, 'Bac'),
  ('Diplôme d\'Ingénieur Humanité numérique', 19, 'Bac'),
  ('Doctorat Population et santé', 3, 'Master'),
  ('DIPES I Lettres billingues', 16, 'Licence'),
  ('DIPES II Lettres billingues', 16, 'Master'),
  ('DIPES I Langues et cultures camerounaises', 16, 'Licence'),
  ('DIPES II Langues et cultures camerounaises', 16, 'Master'),
  ('DEUG Physiques', 12, 'Bac'),
  ('DEUG Sciences de l\'ingénieur', 12, 'Bac'),
  ('Diplôme d\'Ingénieur de Travaux Réseaux et télécommunications', 32, 'Bac'),
  ('Diplôme d\'Ingénieur de Travaux Génie électronique et électricité', 32, 'Bac'),
  ('Master Génie électronique et électricité', 20, 'Licence'),
  ('Doctorat Génie électronique et électricité', 3, 'Master'),
  ('Doctorat Télécommunications', 3, 'Master'),
  ('DIPCO Conseillers d´orientation', 32, 'Bac'),
  ('DESS Sciences et techniques des activités physiques et sportives', 22, 'Master'),
  ('DESS Anesthésie-réanimation', 22, 'Master'),
  ('Doctorat Anesthésie-réanimation', 3, 'Master'),
  ('DESS Chirurgie générale', 22, 'Master'),
  ('Doctorat Chirurgie générale', 3, 'Master'),
  ('DESS Médecine interne et spécialités', 22, 'Master'),
  ('Doctorat Médecine interne et spécialités', 3, 'Master'),
  ('Doctorat Radiologie et imagerie médicale', 3, 'Master'),
  ('DESS Oto-rhino-laryngologie', 22, 'Master'),
  ('Doctorat Oto-rhino-laryngologie', 3, 'Master'),
  ('CJA Conseiller de jeunesse et d\'animation', 16, 'Bac'),
  ('CAPEPS II Professeur certifiés d\'éducation physique et sportive', 16, 'Licence'),
  ('ISE Ingénieur statisticiens économiste', 19, 'Licence'),
  ('Bachelor Technicien de la statistique', 14, 'Bacc'),
  ('Diplôme d\'Ingénieur de Travaux Radiocommunication', 32, 'Bac'),
  ('Diplôme d\'Ingénieur de Travaux Informatique et réseaux', 32, 'Bac'),
  ('Diplôme d\'Ingénieur de Travaux Génie informatique', 32, 'Bac'),
  ('Diplôme d\'Ingénieur de Travaux Génie industriel', 32, 'Bac'),
  ('Doctorat Génie industriel', 3, 'Master');
COMMIT;

START TRANSACTION;
INSERT IGNORE INTO diplomes (nom_dip, categorie_id, niveau) VALUES
  ('Doctorat en Médecine/Pharmacie/Buccodentaire Études médico-sanitaire et biomédicale', 3, 'Bac'),
  ('Doctorat en Médecine/Pharmacie/Buccodentaire Médecine bucco-dentaire', 3, 'Bac'),
  ('DESS Sciences et techniques de l\'animation', 22, 'Master'),
  ('DESS Anatomie pathologique', 22, 'Master'),
  ('Doctorat Anatomie pathologique', 3, 'Master'),
  ('Doctorat Biologie clinique', 3, 'Master'),
  ('DESS Gynéco-obstétrique', 22, 'Master'),
  ('Doctorat Gynéco-obstétrique', 3, 'Master'),
  ('Doctorat Pédiatrie', 3, 'Master'),
  ('Doctorat Ophtalmologie', 3, 'Master'),
  ('DESS Radiothérapie', 22, 'Master'),
  ('Doctorat Radiothérapie', 3, 'Master'),
  ('CAPEPS I Professeur adjoints d\'éducation physique et sportive', 16, 'Licence'),
  ('CPJA Conseiller principal de jeunesse et d\'animation', 16, 'Licence'),
  ('Diplôme d\'Ingénieur des Travaux Statistiques Ingénieur d\'application de la statistique', 32, 'Bac'),
  ('BTS Comptabilité et gestion des entreprises (CGE)', 5, 'Bac'),
  ('BTS Informatique industrielle (II)', 5, 'Bac'),
  ('BTS Construction mécanique (CM)', 5, 'Bac'),
  ('BTS Action commerciale (AC)', 5, 'Bac'),
  ('BTS Fabrication mécanique (FM)', 5, 'Bac'),
  ('BTS Électrotechnique (ET)', 5, 'Bac'),
  ('Licence Physiologie végétales', 17, 'Bacc'),
  ('Master Physiologie végétales', 20, 'Licence'),
  ('Licence Électronique-électrotechnique-automatique', 17, 'Bacc'),
  ('Master Électronique-électrotechnique-automatique', 20, 'Licence'),
  ('Doctorat Électronique-électrotechnique-automatique', 3, 'Master'),
  ('Licence Géotechnique et valorisation des matériaux', 17, 'Bacc'),
  ('Master Géotechnique et valorisation des matériaux', 20, 'Licence'),
  ('Doctorat Géotechnique et valorisation des matériaux', 3, 'Master'),
  ('Licence Hydrologie et aménagement des ressources naturelles', 17, 'Bacc'),
  ('Master Hydrologie et aménagement des ressources naturelles', 20, 'Licence'),
  ('Doctorat Hydrologie et aménagement des ressources naturelles', 3, 'Master'),
  ('Licence Sciences agricoles', 17, 'Bacc'),
  ('Master Afrique et mondialisation', 20, 'Licence'),
  ('Master Linguistique appliquée aux langues africaines', 20, 'Licence'),
  ('Master Études hispaniques et ibériques', 20, 'Licence'),
  ('Master Études françaises et francophones', 20, 'Licence'),
  ('Master Territoire-développement-environnement', 20, 'Licence'),
  ('Master Comptabilité-contrôle-audit', 20, 'Licence'),
  ('Doctorat Comptabilité-contrôle-audit', 3, 'Master'),
  ('Master Monnaie-finance-banque', 20, 'Licence'),
  ('Doctorat Monnaie-finance-banque', 3, 'Master'),
  ('Master Économie mathématiques', 20, 'Licence'),
  ('Doctorat Économie mathématiques', 3, 'Master'),
  ('Master Droit et carrière juridique (DCJ)', 20, 'Licence'),
  ('Doctorat Droit et carrière juridique (DCJ)', 3, 'Master'),
  ('Master Droit communautaire et comparé CEMAC', 20, 'Licence'),
  ('Doctorat Droit communautaire et comparé CEMAC', 3, 'Master'),
  ('Master Droit et carrières administratives', 20, 'Licence'),
  ('Doctorat Sciences du langage, littératures et cultures', 3, 'Master');
COMMIT;

START TRANSACTION;
INSERT IGNORE INTO diplomes (nom_dip, categorie_id, niveau) VALUES
  ('Capacité en Droit Capacité en droit (filière anglophone)', 28, 'Bac'),
  ('DEUP Sciences de gestion des entreprises agricoles', 25, 'Bac'),
  ('Licence Mécanique-énergétique', 17, 'Bacc'),
  ('Master Mécanique-énergétique', 20, 'Licence'),
  ('Doctorat Mécanique-énergétique', 3, 'Master'),
  ('Licence Matière  condensée', 17, 'Bacc'),
  ('Master Matière  condensée', 20, 'Licence'),
  ('Doctorat Matière  condensée', 3, 'Master'),
  ('Licence Agronomie', 17, 'Bacc'),
  ('Master English and commonwealth studies', 20, 'Licence'),
  ('Master Études italiennes', 20, 'Licence'),
  ('Master Dynamique des espaces tropicaux et développement', 20, 'Licence'),
  ('Master Philosophie-sociologie', 20, 'Licence'),
  ('Doctorat Philosophie-sociologie', 3, 'Master'),
  ('Master Économie publique des ressources humaines', 20, 'Licence'),
  ('Doctorat Économie publique des ressources humaines', 3, 'Master'),
  ('Master Droit d\'inspiration romaniste', 20, 'Licence'),
  ('Master Droit des affaires et de l\'entreprise (DAE)', 20, 'Licence'),
  ('Doctorat Droit des affaires et de l\'entreprise (DAE)', 3, 'Master'),
  ('Master Droit de l\'homme, droit international humanitaire', 20, 'Licence'),
  ('Doctorat Droit de l\'homme, droit international humanitaire', 3, 'Master'),
  ('Capacité en Droit Capacité en droit (filière francophone)', 28, 'Bac'),
  ('DEUP Productions animales', 25, 'Bac'),
  ('Master Pro Droit et pratique des contentieux', 22, 'Licence'),
  ('Master Pro Sciences et techniques comptables et financières', 22, 'Licence'),
  ('Master Pro Administration et gestion des collectivités locale', 22, 'Licence'),
  ('Master Pro Administration des entresprises', 22, 'Licence'),
  ('Master Pro Géographie des problémes d\'environnement et d\'amén', 22, 'Licence'),
  ('Master Pro Organisation et management', 22, 'Licence'),
  ('Master Pro Gouvernance, gestion des ressources et résolution', 22, 'Licence'),
  ('Master Pro Psychologie', 22, 'Licence'),
  ('Master Pro Techniques de gestion de la pme-pmi', 22, 'Licence'),
  ('Licence Lettres trillingues français-anglais-allemand', 17, 'Bacc'),
  ('Licence Lettres trillingues français-anglais-italien', 17, 'Bacc'),
  ('Licence Archivistique, documentation et librairie', 17, 'Bacc'),
  ('Licence Cartographie, topographie et systèmes d\'informatio', 17, 'Bacc'),
  ('Licence Analyse et politiques économiques (APE)', 17, 'Bacc'),
  ('Licence Droit privé et sciences criminelles', 17, 'Bacc'),
  ('Licence Biochimie clinique', 17, 'Bacc'),
  ('Master Biochimie clinique', 20, 'Licence'),
  ('Doctorat Biochimie clinique', 3, 'Master'),
  ('Licence Pharmacologie', 17, 'Bacc'),
  ('Master Pharmacologie', 20, 'Licence'),
  ('Doctorat Pharmacologie', 3, 'Master'),
  ('Doctorat Chimie inorganique', 3, 'Master'),
  ('Licence Lettres billingues français-anglais', 17, 'Bacc'),
  ('Licence Lettres trillingues français-anglais-espagnol', 17, 'Bacc'),
  ('Licence Tourisme, guides et interprètes', 17, 'Bacc'),
  ('Licence Sciences de gestion (SG)', 17, 'Bacc'),
  ('Licence Gestion des ressources humaines (GRH)', 17, 'Bacc');
COMMIT;

START TRANSACTION;
INSERT IGNORE INTO diplomes (nom_dip, categorie_id, niveau) VALUES
  ('Master Gestion des ressources humaines (GRH)', 20, 'Licence'),
  ('Doctorat Gestion des ressources humaines (GRH)', 3, 'Master'),
  ('Licence Droit public et sciences politiques', 17, 'Bacc'),
  ('Licence Physiologie animale', 17, 'Bacc'),
  ('Licence Nutrition et sécurité alimentaires', 17, 'Bacc'),
  ('Master Nutrition et sécurité alimentaires', 20, 'Licence'),
  ('Doctorat Nutrition et sécurité alimentaires', 3, 'Master'),
  ('Doctorat Chimie organique', 3, 'Master'),
  ('DSEP Télécommunications et réseaux', 25, 'Bac'),
  ('BTS Études médico-sanitaires et biomédicales', 5, 'Bac'),
  ('DSEP Études médico-sanitaires et biomédicales', 25, 'Bac'),
  ('BTS Imagerie médicale', 5, 'Bac'),
  ('DSEP Imagerie médicale', 25, 'Bac'),
  ('DSEP Odontostomatologie', 25, 'Bac'),
  ('BTS Soins infirmiers', 5, 'Bac'),
  ('DSEP Soins infirmiers', 25, 'Bac'),
  ('DSEP Action commerciale', 25, 'Bac'),
  ('DSEP Banque', 25, 'Bac'),
  ('DSEP Comptabilité et gestion des entreprises', 25, 'Bac'),
  ('DIPET I Agriculture et agro-pastoral', 16, 'Licence'),
  ('DIPET II Agriculture et agro-pastoral', 16, 'Master'),
  ('DIPET I Maintenance informatique', 16, 'Licence'),
  ('DIPET I Management de l´information et des organisations', 16, 'Licence'),
  ('DIPET I Industrie du textile et de l\'habillement', 16, 'Licence'),
  ('DIPET II Industrie du textile et de l\'habillement', 16, 'Master'),
  ('BTS Informatique', 5, 'Bac'),
  ('DSEP Informatique', 25, 'Bac'),
  ('BTS Études médicales', 5, 'Bac'),
  ('DSEP Études médicales', 25, 'Bac'),
  ('BTS Études pharmaceutiques', 5, 'Bac'),
  ('DSEP Études pharmaceutiques', 25, 'Bac'),
  ('DSEP Kinésithérapie', 25, 'Bac'),
  ('BTS Santé publique', 5, 'Bac'),
  ('DSEP Santé publique', 25, 'Bac'),
  ('BTS Technique de laboratoire médical', 5, 'Bac'),
  ('DSEP Technique de laboratoire médical', 25, 'Bac'),
  ('DSEP Assurances', 25, 'Bac'),
  ('DSEP Commerce international', 25, 'Bac'),
  ('DSEP Informatique de gestion', 25, 'Bac'),
  ('DIPET I Maintenance et installation des systèmes électroniques', 16, 'Licence'),
  ('DIPET I Nutrition humaine et diététique', 16, 'Licence'),
  ('DIPET I Gestion financière et comptable', 16, 'Licence'),
  ('DIPET II Gestion financière et comptable', 16, 'Master'),
  ('DIPET I Économie', 16, 'Licence'),
  ('DIPET II Économie', 16, 'Master'),
  ('Licence Droit privé francophone', 17, 'Bacc'),
  ('Licence Administration et gestion des entreprises', 17, 'Bacc'),
  ('Master Administration et gestion des entreprises', 20, 'Licence'),
  ('Licence Ingénierie économique', 17, 'Bacc'),
  ('Master Business law (common law)', 20, 'Licence');
COMMIT;

START TRANSACTION;
INSERT IGNORE INTO diplomes (nom_dip, categorie_id, niveau) VALUES
  ('Master Droit de la propriété intellectuelle', 20, 'Licence'),
  ('Master Systèmes électoraux, idéologies et partis politiques', 20, 'Licence'),
  ('Master Administration publique', 20, 'Licence'),
  ('Master Macroéconomie monétaire et financière', 20, 'Licence'),
  ('Master Économie internationale', 20, 'Licence'),
  ('Master Microéconomie du développement', 20, 'Licence'),
  ('Master Mathématiques-statistiques appliquées aux sciences sociales', 20, 'Licence'),
  ('Master Management stratégique', 20, 'Licence'),
  ('Doctorat Marketing', 3, 'Master'),
  ('Master Économie et gestion appliquée', 20, 'Licence'),
  ('Master Marketing et management des organisation', 20, 'Licence'),
  ('Master Politiques et négociations commerciales multilatérales', 20, 'Licence'),
  ('Licence Common law', 17, 'Bacc'),
  ('Licence Banque, monnaie et finance', 17, 'Bacc'),
  ('Master Philosophie du droit (common law)', 20, 'Licence'),
  ('Master Droit des affaires internationales et fiscalité', 20, 'Licence'),
  ('Master Institutions, relations internationales et études stratégiques', 20, 'Licence'),
  ('Master Socio-anthropologie politique', 20, 'Licence'),
  ('Master Économie politique', 20, 'Licence'),
  ('Master Stratégie, défense, sécurité, gestion des conflits et des catastrophes', 20, 'Licence'),
  ('Master Gouvernance et développement économique', 20, 'Licence'),
  ('Master Ingénierie économique et financière', 20, 'Licence'),
  ('Master Économie de l´environnement, du développement rural et de l´agroalimentaire.', 20, 'Licence'),
  ('Master Finance et comptabilité', 20, 'Licence'),
  ('Doctorat Finance et comptabilité', 3, 'Master'),
  ('Master Développement et gouvernance des institutions locales', 20, 'Licence'),
  ('Master Politique publique et developpement durable', 20, 'Licence'),
  ('Master Gouvernance financière', 20, 'Licence'),
  ('Licence Pro Enseignement des langues et cultures camerounaises', 18, 'Bacc'),
  ('Master Pro Nutrition clinique et diététique', 22, 'Licence'),
  ('Master Pro Assainissement urbain', 22, 'Licence'),
  ('Master Pro Mines et pétrole', 22, 'Licence'),
  ('Master Pro Traduction interprétariat français-anglais-alleman', 22, 'Licence'),
  ('Master Pro Traduction interprétariat français-anglais-italien', 22, 'Licence'),
  ('Master Pro Migrations internationales et développement local', 22, 'Licence'),
  ('Master Pro Cartographie et télédétection', 22, 'Licence'),
  ('Master Pro Banque-assurance-bourse', 22, 'Licence'),
  ('Master Pro Administration des affaires', 22, 'Licence'),
  ('Master Pro Contentieux administratif, financier et douanier', 22, 'Licence'),
  ('Licence Pro Ingénierie juridique des collectivités locales', 18, 'Bacc'),
  ('Master Pro Nutrition communautaire', 22, 'Licence'),
  ('Master Pro Gouvernance locale, décentralisation et développem', 22, 'Licence'),
  ('Master Pro Traduction interprétariat français-anglais-espagno', 22, 'Licence'),
  ('Master Pro Traduction interprétariat français-anglais-franÃ§ai', 22, 'Licence'),
  ('Master Pro Changements climatiques, bio-diversité et économie', 22, 'Licence'),
  ('Master Pro Comptabilité-fiscalité', 22, 'Licence'),
  ('Master Pro Marketing', 22, 'Licence'),
  ('Master Pro Droit, pratique et contentieux des assurances', 22, 'Licence'),
  ('Doctorat Contrôle de gestion', 3, 'Master'),
  ('Doctorat Monnaie, banque, finance', 3, 'Master');
COMMIT;

START TRANSACTION;
INSERT IGNORE INTO diplomes (nom_dip, categorie_id, niveau) VALUES
  ('Doctorat Économie du travail', 3, 'Master'),
  ('Doctorat Économie agricole', 3, 'Master'),
  ('DESS Droit notorial', 22, 'Master'),
  ('Licence Pro Techniques de ventes', 18, 'Bacc'),
  ('Licence Pro Gestion des collectivités territoriales', 18, 'Bacc'),
  ('Licence Pro Négociation et promotion immobilière', 18, 'Bacc'),
  ('Licence Pro Logistique de transport et déclarant en douane.', 18, 'Bacc'),
  ('Master Pro Économie de l´environnement, du développement rural et de l´agroalimentaire', 22, 'Licence'),
  ('Master Pro Gestion bancaires et des établissements financiers', 22, 'Licence'),
  ('Master Pro Politiques urbaines et des collectivités territoriales décentralisées', 22, 'Licence'),
  ('Master Pro Intelligence économique, innovation, entrepreneuriat et développement des pme', 22, 'Licence'),
  ('Master Pro Économie solidaires et microfinance', 22, 'Licence'),
  ('Doctorat Gestion des ressources humaines management-stratégique', 3, 'Master'),
  ('Doctorat Économie de développement', 3, 'Master'),
  ('Doctorat Économie internationale', 3, 'Master'),
  ('Licence Pro Pratique fiscale', 18, 'Bacc'),
  ('Licence Pro Gestion des microfinances', 18, 'Bacc'),
  ('Licence Pro Métiers de l´entreprenariat et développement de la pme', 18, 'Bacc'),
  ('Master Pro Expertise et techniques de négociations en commerce international', 22, 'Licence'),
  ('Master Pro Économie des transports et logistique des échanges', 22, 'Licence'),
  ('Master Pro Gestion de la politique économique', 22, 'Licence'),
  ('Licence Pro Guide touristique et management des entreprises touristique et hôtelières', 18, 'Bacc'),
  ('Licence Pro Chirurgie endoscopique et reproduction humaine', 18, 'Bacc'),
  ('Master Pro Chirurgie endoscopique et reproduction humaine', 22, 'Licence'),
  ('Doctorat Chirurgie endoscopique et reproduction humaine', 3, 'Master'),
  ('Licence Pro Pharmacie et santé publique', 18, 'Bacc'),
  ('Master Pro Pharmacie et santé publique', 22, 'Licence'),
  ('Doctorat Pharmacie et santé publique', 3, 'Master'),
  ('Licence Pro Management de l\'assurance qualité', 18, 'Bacc'),
  ('Master Pro Management de l\'assurance qualité', 22, 'Licence'),
  ('Doctorat Management de l\'assurance qualité', 3, 'Master'),
  ('Licence Pro Médecine d\'urgence et de catastrophes', 18, 'Bacc'),
  ('Master Pro Médecine d\'urgence et de catastrophes', 22, 'Licence'),
  ('Doctorat Médecine d\'urgence et de catastrophes', 3, 'Master'),
  ('Licence Pro Échographie', 18, 'Bacc'),
  ('Master Pro Échographie', 22, 'Licence'),
  ('Doctorat Échographie', 3, 'Master'),
  ('Licence Pro Prise en charge du vih/sida', 18, 'Bacc'),
  ('Master Pro Prise en charge du vih/sida', 22, 'Licence'),
  ('Doctorat Prise en charge du vih/sida', 3, 'Master'),
  ('BTS Sécurités des réseaux', 5, 'Bac'),
  ('BTS Services et radio mobile', 5, 'Bac'),
  ('Licence Arts plastiques', 17, 'Bacc'),
  ('Licence Arts décoratifs', 17, 'Bacc'),
  ('Licence Stylisme modélisme et arts textiles', 17, 'Bacc'),
  ('Master Stylisme modélisme et arts textiles', 20, 'Licence'),
  ('Licence Musique', 17, 'Bacc'),
  ('Licence Cinéma et audio-visuelle', 17, 'Bacc'),
  ('Master Cinéma et audio-visuelle', 20, 'Licence'),
  ('Licence Histoire de l´art: métier des expositions et technologie de l´information', 17, 'Bacc');
COMMIT;

START TRANSACTION;
INSERT IGNORE INTO diplomes (nom_dip, categorie_id, niveau) VALUES
  ('Licence Arts, technologie et patrimoine', 17, 'Bacc'),
  ('Licence Architecture et arts de l´ingénieur', 17, 'Bacc'),
  ('Licence Architecture', 17, 'Bacc'),
  ('Master Architecture', 20, 'Licence'),
  ('Master Arts décoratifs', 20, 'Licence'),
  ('Licence Théâtre', 17, 'Bacc'),
  ('Licence Dessin peinture', 17, 'Bacc'),
  ('Master Dessin peinture', 20, 'Licence'),
  ('Licence Sculpture-céramique-gravure', 17, 'Bacc'),
  ('DIPET I Exploitation forestière et gestion durable', 16, 'Licence'),
  ('Licence Pro Informatique', 18, 'Bacc'),
  ('Master Pro Informatique', 22, 'Licence'),
  ('Licence Pro Études médico-sanitaires et biomédicales', 18, 'Bacc'),
  ('Master Pro Études médico-sanitaires et biomédicales', 22, 'Licence'),
  ('Doctorat Études médico-sanitaires et biomédicales', 3, 'Master'),
  ('Licence Pro Imagerie médicale', 18, 'Bacc'),
  ('Master Pro Imagerie médicale', 22, 'Licence'),
  ('Doctorat Imagerie médicale', 3, 'Master'),
  ('Doctorat Odontostomatologie', 3, 'Master'),
  ('Licence Pro Soins infirmiers', 18, 'Bacc'),
  ('Master Pro Soins infirmiers', 22, 'Licence'),
  ('Master Pro Action commerciale', 22, 'Licence'),
  ('Doctorat Action commerciale', 3, 'Master'),
  ('Master Pro Banque', 22, 'Licence'),
  ('Doctorat Banque', 3, 'Master'),
  ('Master Pro Comptabilité et gestion des entreprises', 22, 'Licence'),
  ('Doctorat Comptabilité et gestion des entreprises', 3, 'Master'),
  ('Licence Pro Médecine générale', 18, 'Bacc'),
  ('Master Pro Médecine générale', 22, 'Licence'),
  ('Licence Pro Pharmacie', 18, 'Bacc'),
  ('Master Pro Pharmacie', 22, 'Licence'),
  ('DIPET II Tourisme', 16, 'Master'),
  ('Licence Pro Études médicales', 18, 'Bacc'),
  ('Master Pro Études médicales', 22, 'Licence'),
  ('Doctorat Études médicales', 3, 'Master'),
  ('Licence Pro Études pharmaceutiques', 18, 'Bacc'),
  ('Master Pro Études pharmaceutiques', 22, 'Licence'),
  ('Doctorat Études pharmaceutiques', 3, 'Master'),
  ('Licence Pro Technique de laboratoire médical', 18, 'Bacc'),
  ('Master Pro Technique de laboratoire médical', 22, 'Licence'),
  ('Doctorat Technique de laboratoire médical', 3, 'Master'),
  ('Master Pro Assurances', 22, 'Licence'),
  ('Doctorat Assurances', 3, 'Master'),
  ('Master Pro Commerce international', 22, 'Licence'),
  ('Doctorat Commerce international', 3, 'Master'),
  ('Doctorat Informatique de gestion', 3, 'Master'),
  ('Licence Pro Sciences de la santé', 18, 'Bacc'),
  ('Master Pro Sciences de la santé', 22, 'Licence'),
  ('Doctorat Sciences de la santé', 3, 'Master'),
  ('Licence Gestion des pêches', 17, 'Bacc');
COMMIT;

START TRANSACTION;
INSERT IGNORE INTO diplomes (nom_dip, categorie_id, niveau) VALUES
  ('Master Gestion des pêches', 20, 'Licence'),
  ('Doctorat Gestion des pêches', 3, 'Master'),
  ('Licence Gestion des écosystèmes aquatiques', 17, 'Bacc'),
  ('Master Gestion des écosystèmes aquatiques', 20, 'Licence'),
  ('Doctorat Gestion des écosystèmes aquatiques', 3, 'Master'),
  ('Licence Océanographie et limonologie', 17, 'Bacc'),
  ('Master Océanographie et limonologie', 20, 'Licence'),
  ('Doctorat Océanographie et limonologie', 3, 'Master'),
  ('Licence Aquaculture', 17, 'Bacc'),
  ('Master Aquaculture', 20, 'Licence'),
  ('Doctorat Aquaculture', 3, 'Master'),
  ('Licence Transformation et contrôle de qualité des produits', 17, 'Bacc'),
  ('Master Transformation et contrôle de qualité des produits', 20, 'Licence'),
  ('Doctorat Transformation et contrôle de qualité des produits', 3, 'Master'),
  ('Master Ophtalmologie, orl et stomatologie', 20, 'Licence'),
  ('Doctorat Ophtalmologie, orl et stomatologie', 3, 'Master'),
  ('Master Microbiologie, parasitologie, hématologie et maladies infectueuses', 20, 'Licence'),
  ('Doctorat Microbiologie, parasitologie, hématologie et maladies infectueuses', 3, 'Master'),
  ('Master Sciences morphologiques et anatomie pathologique', 20, 'Licence'),
  ('Doctorat Sciences morphologiques et anatomie pathologique', 3, 'Master'),
  ('Master Radiologie et imagerie médicale', 20, 'Licence'),
  ('Doctorat Chirurgie et spécialités', 3, 'Master'),
  ('Master Pro Stratégie et création publicitaire', 22, 'Licence'),
  ('Master Pro Communication et coopération internationale', 22, 'Licence'),
  ('Master Pro Démographie', 22, 'Licence'),
  ('Master Pro Système d´information géographique', 22, 'Licence'),
  ('Master Pro Genre et développement', 22, 'Licence'),
  ('Master Pro Production cinématographique', 22, 'Licence'),
  ('Master Pro Traduction et interprétation', 22, 'Licence'),
  ('Master Pro Psychologie du travail  des l´organisation', 22, 'Licence'),
  ('Master Pro Psychologie scolaire', 22, 'Licence'),
  ('Master Pro Communication sur la santé et l´environnement', 22, 'Licence'),
  ('Master Pro Communication stratégique pour la paix, l´émergence et le développement durable', 22, 'Licence'),
  ('Master Pro Urbanisme, aménagement, développement urbain', 22, 'Licence'),
  ('Master Pro Langue africaine', 22, 'Licence'),
  ('Doctorat Langue africaine', 3, 'Master'),
  ('Master Pro Sciences sociales pour le développement', 22, 'Licence'),
  ('Master Pro Aménagement touristique des territoires', 22, 'Licence'),
  ('Master Pro Psychologie appliquée à l´enfant et à l´adolescent', 22, 'Licence'),
  ('Master Pro Sémiotique', 22, 'Licence');
COMMIT;
